// Code generated by go-swagger; DO NOT EDIT.

package certificates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteCertificateReader is a Reader for the DeleteCertificate structure.
type DeleteCertificateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteCertificateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteCertificateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteCertificateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteCertificateOK creates a DeleteCertificateOK with default headers values
func NewDeleteCertificateOK() *DeleteCertificateOK {
	return &DeleteCertificateOK{}
}

/*DeleteCertificateOK handles this case with default header values.

OK
*/
type DeleteCertificateOK struct {
}

func (o *DeleteCertificateOK) Error() string {
	return fmt.Sprintf("[DELETE /api/certificates/{id}][%d] deleteCertificateOK ", 200)
}

func (o *DeleteCertificateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteCertificateBadRequest creates a DeleteCertificateBadRequest with default headers values
func NewDeleteCertificateBadRequest() *DeleteCertificateBadRequest {
	return &DeleteCertificateBadRequest{}
}

/*DeleteCertificateBadRequest handles this case with default header values.

BadRequest
No id parameter was provided.
This resource is read-only and cannot be deleted.
*/
type DeleteCertificateBadRequest struct {
}

func (o *DeleteCertificateBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /api/certificates/{id}][%d] deleteCertificateBadRequest ", 400)
}

func (o *DeleteCertificateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
