// Code generated by go-swagger; DO NOT EDIT.

package certificates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// GetCertificateUsageSpacesReader is a Reader for the GetCertificateUsageSpaces structure.
type GetCertificateUsageSpacesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCertificateUsageSpacesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCertificateUsageSpacesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetCertificateUsageSpacesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetCertificateUsageSpacesOK creates a GetCertificateUsageSpacesOK with default headers values
func NewGetCertificateUsageSpacesOK() *GetCertificateUsageSpacesOK {
	return &GetCertificateUsageSpacesOK{}
}

/*GetCertificateUsageSpacesOK handles this case with default header values.

CertificateUsageResource resource returned
*/
type GetCertificateUsageSpacesOK struct {
	Payload *models.CertificateUsageResource
}

func (o *GetCertificateUsageSpacesOK) Error() string {
	return fmt.Sprintf("[GET /api/{baseSpaceId}/certificates/{id}/usages][%d] getCertificateUsageSpacesOK  %+v", 200, o.Payload)
}

func (o *GetCertificateUsageSpacesOK) GetPayload() *models.CertificateUsageResource {
	return o.Payload
}

func (o *GetCertificateUsageSpacesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CertificateUsageResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCertificateUsageSpacesBadRequest creates a GetCertificateUsageSpacesBadRequest with default headers values
func NewGetCertificateUsageSpacesBadRequest() *GetCertificateUsageSpacesBadRequest {
	return &GetCertificateUsageSpacesBadRequest{}
}

/*GetCertificateUsageSpacesBadRequest handles this case with default header values.

No id parameter was provided.
*/
type GetCertificateUsageSpacesBadRequest struct {
}

func (o *GetCertificateUsageSpacesBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/{baseSpaceId}/certificates/{id}/usages][%d] getCertificateUsageSpacesBadRequest ", 400)
}

func (o *GetCertificateUsageSpacesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
