// Code generated by go-swagger; DO NOT EDIT.

package packages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCreatePackageRepositoryUploadParams creates a new CreatePackageRepositoryUploadParams object
// with the default values initialized.
func NewCreatePackageRepositoryUploadParams() *CreatePackageRepositoryUploadParams {

	return &CreatePackageRepositoryUploadParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreatePackageRepositoryUploadParamsWithTimeout creates a new CreatePackageRepositoryUploadParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreatePackageRepositoryUploadParamsWithTimeout(timeout time.Duration) *CreatePackageRepositoryUploadParams {

	return &CreatePackageRepositoryUploadParams{

		timeout: timeout,
	}
}

// NewCreatePackageRepositoryUploadParamsWithContext creates a new CreatePackageRepositoryUploadParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreatePackageRepositoryUploadParamsWithContext(ctx context.Context) *CreatePackageRepositoryUploadParams {

	return &CreatePackageRepositoryUploadParams{

		Context: ctx,
	}
}

// NewCreatePackageRepositoryUploadParamsWithHTTPClient creates a new CreatePackageRepositoryUploadParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreatePackageRepositoryUploadParamsWithHTTPClient(client *http.Client) *CreatePackageRepositoryUploadParams {

	return &CreatePackageRepositoryUploadParams{
		HTTPClient: client,
	}
}

/*CreatePackageRepositoryUploadParams contains all the parameters to send to the API endpoint
for the create package repository upload operation typically these are written to a http.Request
*/
type CreatePackageRepositoryUploadParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create package repository upload params
func (o *CreatePackageRepositoryUploadParams) WithTimeout(timeout time.Duration) *CreatePackageRepositoryUploadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create package repository upload params
func (o *CreatePackageRepositoryUploadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create package repository upload params
func (o *CreatePackageRepositoryUploadParams) WithContext(ctx context.Context) *CreatePackageRepositoryUploadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create package repository upload params
func (o *CreatePackageRepositoryUploadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create package repository upload params
func (o *CreatePackageRepositoryUploadParams) WithHTTPClient(client *http.Client) *CreatePackageRepositoryUploadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create package repository upload params
func (o *CreatePackageRepositoryUploadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *CreatePackageRepositoryUploadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
