// Code generated by go-swagger; DO NOT EDIT.

package packages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeletePackageRepositoryDeleteByIdsReader is a Reader for the DeletePackageRepositoryDeleteByIds structure.
type DeletePackageRepositoryDeleteByIdsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeletePackageRepositoryDeleteByIdsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeletePackageRepositoryDeleteByIdsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeletePackageRepositoryDeleteByIdsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeletePackageRepositoryDeleteByIdsOK creates a DeletePackageRepositoryDeleteByIdsOK with default headers values
func NewDeletePackageRepositoryDeleteByIdsOK() *DeletePackageRepositoryDeleteByIdsOK {
	return &DeletePackageRepositoryDeleteByIdsOK{}
}

/*DeletePackageRepositoryDeleteByIdsOK handles this case with default header values.

OK
*/
type DeletePackageRepositoryDeleteByIdsOK struct {
}

func (o *DeletePackageRepositoryDeleteByIdsOK) Error() string {
	return fmt.Sprintf("[DELETE /api/packages/bulk][%d] deletePackageRepositoryDeleteByIdsOK ", 200)
}

func (o *DeletePackageRepositoryDeleteByIdsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeletePackageRepositoryDeleteByIdsBadRequest creates a DeletePackageRepositoryDeleteByIdsBadRequest with default headers values
func NewDeletePackageRepositoryDeleteByIdsBadRequest() *DeletePackageRepositoryDeleteByIdsBadRequest {
	return &DeletePackageRepositoryDeleteByIdsBadRequest{}
}

/*DeletePackageRepositoryDeleteByIdsBadRequest handles this case with default header values.

No ids parameter was provided.
*/
type DeletePackageRepositoryDeleteByIdsBadRequest struct {
}

func (o *DeletePackageRepositoryDeleteByIdsBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /api/packages/bulk][%d] deletePackageRepositoryDeleteByIdsBadRequest ", 400)
}

func (o *DeletePackageRepositoryDeleteByIdsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
