// Code generated by go-swagger; DO NOT EDIT.

package packages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeletePackageRepositoryDeleteByIdsSpacesReader is a Reader for the DeletePackageRepositoryDeleteByIdsSpaces structure.
type DeletePackageRepositoryDeleteByIdsSpacesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeletePackageRepositoryDeleteByIdsSpacesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeletePackageRepositoryDeleteByIdsSpacesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeletePackageRepositoryDeleteByIdsSpacesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeletePackageRepositoryDeleteByIdsSpacesOK creates a DeletePackageRepositoryDeleteByIdsSpacesOK with default headers values
func NewDeletePackageRepositoryDeleteByIdsSpacesOK() *DeletePackageRepositoryDeleteByIdsSpacesOK {
	return &DeletePackageRepositoryDeleteByIdsSpacesOK{}
}

/*DeletePackageRepositoryDeleteByIdsSpacesOK handles this case with default header values.

OK
*/
type DeletePackageRepositoryDeleteByIdsSpacesOK struct {
}

func (o *DeletePackageRepositoryDeleteByIdsSpacesOK) Error() string {
	return fmt.Sprintf("[DELETE /api/{baseSpaceId}/packages/bulk][%d] deletePackageRepositoryDeleteByIdsSpacesOK ", 200)
}

func (o *DeletePackageRepositoryDeleteByIdsSpacesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeletePackageRepositoryDeleteByIdsSpacesBadRequest creates a DeletePackageRepositoryDeleteByIdsSpacesBadRequest with default headers values
func NewDeletePackageRepositoryDeleteByIdsSpacesBadRequest() *DeletePackageRepositoryDeleteByIdsSpacesBadRequest {
	return &DeletePackageRepositoryDeleteByIdsSpacesBadRequest{}
}

/*DeletePackageRepositoryDeleteByIdsSpacesBadRequest handles this case with default header values.

No ids parameter was provided.
*/
type DeletePackageRepositoryDeleteByIdsSpacesBadRequest struct {
}

func (o *DeletePackageRepositoryDeleteByIdsSpacesBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /api/{baseSpaceId}/packages/bulk][%d] deletePackageRepositoryDeleteByIdsSpacesBadRequest ", 400)
}

func (o *DeletePackageRepositoryDeleteByIdsSpacesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
