// Code generated by go-swagger; DO NOT EDIT.

package packages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPackageRepositoryListSpacesParams creates a new GetPackageRepositoryListSpacesParams object
// with the default values initialized.
func NewGetPackageRepositoryListSpacesParams() *GetPackageRepositoryListSpacesParams {
	var ()
	return &GetPackageRepositoryListSpacesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPackageRepositoryListSpacesParamsWithTimeout creates a new GetPackageRepositoryListSpacesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPackageRepositoryListSpacesParamsWithTimeout(timeout time.Duration) *GetPackageRepositoryListSpacesParams {
	var ()
	return &GetPackageRepositoryListSpacesParams{

		timeout: timeout,
	}
}

// NewGetPackageRepositoryListSpacesParamsWithContext creates a new GetPackageRepositoryListSpacesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPackageRepositoryListSpacesParamsWithContext(ctx context.Context) *GetPackageRepositoryListSpacesParams {
	var ()
	return &GetPackageRepositoryListSpacesParams{

		Context: ctx,
	}
}

// NewGetPackageRepositoryListSpacesParamsWithHTTPClient creates a new GetPackageRepositoryListSpacesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetPackageRepositoryListSpacesParamsWithHTTPClient(client *http.Client) *GetPackageRepositoryListSpacesParams {
	var ()
	return &GetPackageRepositoryListSpacesParams{
		HTTPClient: client,
	}
}

/*GetPackageRepositoryListSpacesParams contains all the parameters to send to the API endpoint
for the get package repository list spaces operation typically these are written to a http.Request
*/
type GetPackageRepositoryListSpacesParams struct {

	/*BaseSpaceID
	  ID of the space

	*/
	BaseSpaceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get package repository list spaces params
func (o *GetPackageRepositoryListSpacesParams) WithTimeout(timeout time.Duration) *GetPackageRepositoryListSpacesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get package repository list spaces params
func (o *GetPackageRepositoryListSpacesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get package repository list spaces params
func (o *GetPackageRepositoryListSpacesParams) WithContext(ctx context.Context) *GetPackageRepositoryListSpacesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get package repository list spaces params
func (o *GetPackageRepositoryListSpacesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get package repository list spaces params
func (o *GetPackageRepositoryListSpacesParams) WithHTTPClient(client *http.Client) *GetPackageRepositoryListSpacesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get package repository list spaces params
func (o *GetPackageRepositoryListSpacesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBaseSpaceID adds the baseSpaceID to the get package repository list spaces params
func (o *GetPackageRepositoryListSpacesParams) WithBaseSpaceID(baseSpaceID string) *GetPackageRepositoryListSpacesParams {
	o.SetBaseSpaceID(baseSpaceID)
	return o
}

// SetBaseSpaceID adds the baseSpaceId to the get package repository list spaces params
func (o *GetPackageRepositoryListSpacesParams) SetBaseSpaceID(baseSpaceID string) {
	o.BaseSpaceID = baseSpaceID
}

// WriteToRequest writes these params to a swagger request
func (o *GetPackageRepositoryListSpacesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param baseSpaceId
	if err := r.SetPathParam("baseSpaceId", o.BaseSpaceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
