// Code generated by go-swagger; DO NOT EDIT.

package channels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// CreateChannelSpacesReader is a Reader for the CreateChannelSpaces structure.
type CreateChannelSpacesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateChannelSpacesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateChannelSpacesCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateChannelSpacesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateChannelSpacesCreated creates a CreateChannelSpacesCreated with default headers values
func NewCreateChannelSpacesCreated() *CreateChannelSpacesCreated {
	return &CreateChannelSpacesCreated{}
}

/*CreateChannelSpacesCreated handles this case with default header values.

ChannelResource Created
*/
type CreateChannelSpacesCreated struct {
	Payload *models.ChannelResource
}

func (o *CreateChannelSpacesCreated) Error() string {
	return fmt.Sprintf("[POST /api/{baseSpaceId}/channels][%d] createChannelSpacesCreated  %+v", 201, o.Payload)
}

func (o *CreateChannelSpacesCreated) GetPayload() *models.ChannelResource {
	return o.Payload
}

func (o *CreateChannelSpacesCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ChannelResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateChannelSpacesBadRequest creates a CreateChannelSpacesBadRequest with default headers values
func NewCreateChannelSpacesBadRequest() *CreateChannelSpacesBadRequest {
	return &CreateChannelSpacesBadRequest{}
}

/*CreateChannelSpacesBadRequest handles this case with default header values.

Model validation failed.
No request body was supplied.
*/
type CreateChannelSpacesBadRequest struct {
}

func (o *CreateChannelSpacesBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/{baseSpaceId}/channels][%d] createChannelSpacesBadRequest ", 400)
}

func (o *CreateChannelSpacesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
