// Code generated by go-swagger; DO NOT EDIT.

package channels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// IndexChannelsSpacesReader is a Reader for the IndexChannelsSpaces structure.
type IndexChannelsSpacesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IndexChannelsSpacesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewIndexChannelsSpacesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewIndexChannelsSpacesOK creates a IndexChannelsSpacesOK with default headers values
func NewIndexChannelsSpacesOK() *IndexChannelsSpacesOK {
	return &IndexChannelsSpacesOK{}
}

/*IndexChannelsSpacesOK handles this case with default header values.

ResourceCollection_of_ChannelResource resource returned
*/
type IndexChannelsSpacesOK struct {
	Payload *models.ResourceCollectionOfChannelResource
}

func (o *IndexChannelsSpacesOK) Error() string {
	return fmt.Sprintf("[GET /api/{baseSpaceId}/channels][%d] indexChannelsSpacesOK  %+v", 200, o.Payload)
}

func (o *IndexChannelsSpacesOK) GetPayload() *models.ResourceCollectionOfChannelResource {
	return o.Payload
}

func (o *IndexChannelsSpacesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResourceCollectionOfChannelResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
