// Code generated by go-swagger; DO NOT EDIT.

package channels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// UpdateChannelReader is a Reader for the UpdateChannel structure.
type UpdateChannelReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateChannelReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateChannelOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateChannelBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateChannelOK creates a UpdateChannelOK with default headers values
func NewUpdateChannelOK() *UpdateChannelOK {
	return &UpdateChannelOK{}
}

/*UpdateChannelOK handles this case with default header values.

ChannelResource Modified
*/
type UpdateChannelOK struct {
	Payload *models.ChannelResource
}

func (o *UpdateChannelOK) Error() string {
	return fmt.Sprintf("[PUT /api/channels/{id}][%d] updateChannelOK  %+v", 200, o.Payload)
}

func (o *UpdateChannelOK) GetPayload() *models.ChannelResource {
	return o.Payload
}

func (o *UpdateChannelOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ChannelResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateChannelBadRequest creates a UpdateChannelBadRequest with default headers values
func NewUpdateChannelBadRequest() *UpdateChannelBadRequest {
	return &UpdateChannelBadRequest{}
}

/*UpdateChannelBadRequest handles this case with default header values.

Model validation failed.
No id parameter was provided.
No request body was supplied.
This resource is read-only and cannot be modified.
*/
type UpdateChannelBadRequest struct {
}

func (o *UpdateChannelBadRequest) Error() string {
	return fmt.Sprintf("[PUT /api/channels/{id}][%d] updateChannelBadRequest ", 400)
}

func (o *UpdateChannelBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
