// Code generated by go-swagger; DO NOT EDIT.

package api_keys

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// GetAPIKeyByIDReader is a Reader for the GetAPIKeyByID structure.
type GetAPIKeyByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIKeyByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIKeyByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAPIKeyByIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAPIKeyByIDOK creates a GetAPIKeyByIDOK with default headers values
func NewGetAPIKeyByIDOK() *GetAPIKeyByIDOK {
	return &GetAPIKeyByIDOK{}
}

/*GetAPIKeyByIDOK handles this case with default header values.

Load ApiKeyResource by ID
*/
type GetAPIKeyByIDOK struct {
	Payload *models.APIKeyResource
}

func (o *GetAPIKeyByIDOK) Error() string {
	return fmt.Sprintf("[GET /api/users/{userId}/apikeys/{id}][%d] getApiKeyByIdOK  %+v", 200, o.Payload)
}

func (o *GetAPIKeyByIDOK) GetPayload() *models.APIKeyResource {
	return o.Payload
}

func (o *GetAPIKeyByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIKeyResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIKeyByIDBadRequest creates a GetAPIKeyByIDBadRequest with default headers values
func NewGetAPIKeyByIDBadRequest() *GetAPIKeyByIDBadRequest {
	return &GetAPIKeyByIDBadRequest{}
}

/*GetAPIKeyByIDBadRequest handles this case with default header values.

No id parameter was provided.
No userId parameter was provided.
This ApiKey does not belong to the specified user.
*/
type GetAPIKeyByIDBadRequest struct {
}

func (o *GetAPIKeyByIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/users/{userId}/apikeys/{id}][%d] getApiKeyByIdBadRequest ", 400)
}

func (o *GetAPIKeyByIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
