// Code generated by go-swagger; DO NOT EDIT.

package api_keys

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// IndexAPIKeysReader is a Reader for the IndexAPIKeys structure.
type IndexAPIKeysReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IndexAPIKeysReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewIndexAPIKeysOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewIndexAPIKeysBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewIndexAPIKeysOK creates a IndexAPIKeysOK with default headers values
func NewIndexAPIKeysOK() *IndexAPIKeysOK {
	return &IndexAPIKeysOK{}
}

/*IndexAPIKeysOK handles this case with default header values.

ResourceCollection_of_ApiKeyResource resource returned
*/
type IndexAPIKeysOK struct {
	Payload *models.ResourceCollectionOfAPIKeyResource
}

func (o *IndexAPIKeysOK) Error() string {
	return fmt.Sprintf("[GET /api/users/{userId}/apikeys][%d] indexApiKeysOK  %+v", 200, o.Payload)
}

func (o *IndexAPIKeysOK) GetPayload() *models.ResourceCollectionOfAPIKeyResource {
	return o.Payload
}

func (o *IndexAPIKeysOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResourceCollectionOfAPIKeyResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIndexAPIKeysBadRequest creates a IndexAPIKeysBadRequest with default headers values
func NewIndexAPIKeysBadRequest() *IndexAPIKeysBadRequest {
	return &IndexAPIKeysBadRequest{}
}

/*IndexAPIKeysBadRequest handles this case with default header values.

No userId parameter was provided.
*/
type IndexAPIKeysBadRequest struct {
}

func (o *IndexAPIKeysBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/users/{userId}/apikeys][%d] indexApiKeysBadRequest ", 400)
}

func (o *IndexAPIKeysBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
