// Code generated by go-swagger; DO NOT EDIT.

package deployment_processes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// GetDeploymentProcessByIDReader is a Reader for the GetDeploymentProcessByID structure.
type GetDeploymentProcessByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDeploymentProcessByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDeploymentProcessByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetDeploymentProcessByIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetDeploymentProcessByIDOK creates a GetDeploymentProcessByIDOK with default headers values
func NewGetDeploymentProcessByIDOK() *GetDeploymentProcessByIDOK {
	return &GetDeploymentProcessByIDOK{}
}

/*GetDeploymentProcessByIDOK handles this case with default header values.

Load DeploymentProcessResource by ID
*/
type GetDeploymentProcessByIDOK struct {
	Payload *models.DeploymentProcessResource
}

func (o *GetDeploymentProcessByIDOK) Error() string {
	return fmt.Sprintf("[GET /api/deploymentprocesses/{id}][%d] getDeploymentProcessByIdOK  %+v", 200, o.Payload)
}

func (o *GetDeploymentProcessByIDOK) GetPayload() *models.DeploymentProcessResource {
	return o.Payload
}

func (o *GetDeploymentProcessByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeploymentProcessResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDeploymentProcessByIDBadRequest creates a GetDeploymentProcessByIDBadRequest with default headers values
func NewGetDeploymentProcessByIDBadRequest() *GetDeploymentProcessByIDBadRequest {
	return &GetDeploymentProcessByIDBadRequest{}
}

/*GetDeploymentProcessByIDBadRequest handles this case with default header values.

No id parameter was provided.
*/
type GetDeploymentProcessByIDBadRequest struct {
}

func (o *GetDeploymentProcessByIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/deploymentprocesses/{id}][%d] getDeploymentProcessByIdBadRequest ", 400)
}

func (o *GetDeploymentProcessByIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
