// Code generated by go-swagger; DO NOT EDIT.

package progression

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetProgressionViewSpacesParams creates a new GetProgressionViewSpacesParams object
// with the default values initialized.
func NewGetProgressionViewSpacesParams() *GetProgressionViewSpacesParams {
	var ()
	return &GetProgressionViewSpacesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetProgressionViewSpacesParamsWithTimeout creates a new GetProgressionViewSpacesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetProgressionViewSpacesParamsWithTimeout(timeout time.Duration) *GetProgressionViewSpacesParams {
	var ()
	return &GetProgressionViewSpacesParams{

		timeout: timeout,
	}
}

// NewGetProgressionViewSpacesParamsWithContext creates a new GetProgressionViewSpacesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetProgressionViewSpacesParamsWithContext(ctx context.Context) *GetProgressionViewSpacesParams {
	var ()
	return &GetProgressionViewSpacesParams{

		Context: ctx,
	}
}

// NewGetProgressionViewSpacesParamsWithHTTPClient creates a new GetProgressionViewSpacesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetProgressionViewSpacesParamsWithHTTPClient(client *http.Client) *GetProgressionViewSpacesParams {
	var ()
	return &GetProgressionViewSpacesParams{
		HTTPClient: client,
	}
}

/*GetProgressionViewSpacesParams contains all the parameters to send to the API endpoint
for the get progression view spaces operation typically these are written to a http.Request
*/
type GetProgressionViewSpacesParams struct {

	/*BaseSpaceID
	  ID of the space

	*/
	BaseSpaceID string
	/*ID
	  ID of the resource

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get progression view spaces params
func (o *GetProgressionViewSpacesParams) WithTimeout(timeout time.Duration) *GetProgressionViewSpacesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get progression view spaces params
func (o *GetProgressionViewSpacesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get progression view spaces params
func (o *GetProgressionViewSpacesParams) WithContext(ctx context.Context) *GetProgressionViewSpacesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get progression view spaces params
func (o *GetProgressionViewSpacesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get progression view spaces params
func (o *GetProgressionViewSpacesParams) WithHTTPClient(client *http.Client) *GetProgressionViewSpacesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get progression view spaces params
func (o *GetProgressionViewSpacesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBaseSpaceID adds the baseSpaceID to the get progression view spaces params
func (o *GetProgressionViewSpacesParams) WithBaseSpaceID(baseSpaceID string) *GetProgressionViewSpacesParams {
	o.SetBaseSpaceID(baseSpaceID)
	return o
}

// SetBaseSpaceID adds the baseSpaceId to the get progression view spaces params
func (o *GetProgressionViewSpacesParams) SetBaseSpaceID(baseSpaceID string) {
	o.BaseSpaceID = baseSpaceID
}

// WithID adds the id to the get progression view spaces params
func (o *GetProgressionViewSpacesParams) WithID(id string) *GetProgressionViewSpacesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get progression view spaces params
func (o *GetProgressionViewSpacesParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetProgressionViewSpacesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param baseSpaceId
	if err := r.SetPathParam("baseSpaceId", o.BaseSpaceID); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
