// Code generated by go-swagger; DO NOT EDIT.

package progression

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// GetRunbooksProgressionViewSpacesReader is a Reader for the GetRunbooksProgressionViewSpaces structure.
type GetRunbooksProgressionViewSpacesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRunbooksProgressionViewSpacesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetRunbooksProgressionViewSpacesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetRunbooksProgressionViewSpacesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetRunbooksProgressionViewSpacesOK creates a GetRunbooksProgressionViewSpacesOK with default headers values
func NewGetRunbooksProgressionViewSpacesOK() *GetRunbooksProgressionViewSpacesOK {
	return &GetRunbooksProgressionViewSpacesOK{}
}

/*GetRunbooksProgressionViewSpacesOK handles this case with default header values.

RunbooksProgressionResource resource returned
*/
type GetRunbooksProgressionViewSpacesOK struct {
	Payload *models.RunbooksProgressionResource
}

func (o *GetRunbooksProgressionViewSpacesOK) Error() string {
	return fmt.Sprintf("[GET /api/{baseSpaceId}/progression/runbooks/{id}][%d] getRunbooksProgressionViewSpacesOK  %+v", 200, o.Payload)
}

func (o *GetRunbooksProgressionViewSpacesOK) GetPayload() *models.RunbooksProgressionResource {
	return o.Payload
}

func (o *GetRunbooksProgressionViewSpacesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RunbooksProgressionResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRunbooksProgressionViewSpacesBadRequest creates a GetRunbooksProgressionViewSpacesBadRequest with default headers values
func NewGetRunbooksProgressionViewSpacesBadRequest() *GetRunbooksProgressionViewSpacesBadRequest {
	return &GetRunbooksProgressionViewSpacesBadRequest{}
}

/*GetRunbooksProgressionViewSpacesBadRequest handles this case with default header values.

No id parameter was provided.
*/
type GetRunbooksProgressionViewSpacesBadRequest struct {
}

func (o *GetRunbooksProgressionViewSpacesBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/{baseSpaceId}/progression/runbooks/{id}][%d] getRunbooksProgressionViewSpacesBadRequest ", 400)
}

func (o *GetRunbooksProgressionViewSpacesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
