// Code generated by go-swagger; DO NOT EDIT.

package invitations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetInvitationByIDParams creates a new GetInvitationByIDParams object
// with the default values initialized.
func NewGetInvitationByIDParams() *GetInvitationByIDParams {
	var ()
	return &GetInvitationByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetInvitationByIDParamsWithTimeout creates a new GetInvitationByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetInvitationByIDParamsWithTimeout(timeout time.Duration) *GetInvitationByIDParams {
	var ()
	return &GetInvitationByIDParams{

		timeout: timeout,
	}
}

// NewGetInvitationByIDParamsWithContext creates a new GetInvitationByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetInvitationByIDParamsWithContext(ctx context.Context) *GetInvitationByIDParams {
	var ()
	return &GetInvitationByIDParams{

		Context: ctx,
	}
}

// NewGetInvitationByIDParamsWithHTTPClient creates a new GetInvitationByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetInvitationByIDParamsWithHTTPClient(client *http.Client) *GetInvitationByIDParams {
	var ()
	return &GetInvitationByIDParams{
		HTTPClient: client,
	}
}

/*GetInvitationByIDParams contains all the parameters to send to the API endpoint
for the get invitation by Id operation typically these are written to a http.Request
*/
type GetInvitationByIDParams struct {

	/*ID
	  ID of the InvitationResource to load

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get invitation by Id params
func (o *GetInvitationByIDParams) WithTimeout(timeout time.Duration) *GetInvitationByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get invitation by Id params
func (o *GetInvitationByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get invitation by Id params
func (o *GetInvitationByIDParams) WithContext(ctx context.Context) *GetInvitationByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get invitation by Id params
func (o *GetInvitationByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get invitation by Id params
func (o *GetInvitationByIDParams) WithHTTPClient(client *http.Client) *GetInvitationByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get invitation by Id params
func (o *GetInvitationByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get invitation by Id params
func (o *GetInvitationByIDParams) WithID(id string) *GetInvitationByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get invitation by Id params
func (o *GetInvitationByIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetInvitationByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
