// Code generated by go-swagger; DO NOT EDIT.

package upgrade_configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new upgrade configuration API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for upgrade configuration API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	GetUpgradeConfiguration(params *GetUpgradeConfigurationParams, authInfo runtime.ClientAuthInfoWriter) (*GetUpgradeConfigurationOK, error)

	UpdateUpgradeConfiguration(params *UpdateUpgradeConfigurationParams, authInfo runtime.ClientAuthInfoWriter) (*UpdateUpgradeConfigurationOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GetUpgradeConfiguration Gets information about the upgrade configuration in use by the Octopus Server.
*/
func (a *Client) GetUpgradeConfiguration(params *GetUpgradeConfigurationParams, authInfo runtime.ClientAuthInfoWriter) (*GetUpgradeConfigurationOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetUpgradeConfigurationParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getUpgradeConfiguration",
		Method:             "GET",
		PathPattern:        "/api/upgradeconfiguration",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetUpgradeConfigurationReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetUpgradeConfigurationOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getUpgradeConfiguration: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  UpdateUpgradeConfiguration Updates the upgrade configuration used by the Octopus Server.
*/
func (a *Client) UpdateUpgradeConfiguration(params *UpdateUpgradeConfigurationParams, authInfo runtime.ClientAuthInfoWriter) (*UpdateUpgradeConfigurationOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUpdateUpgradeConfigurationParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "updateUpgradeConfiguration",
		Method:             "PUT",
		PathPattern:        "/api/upgradeconfiguration",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &UpdateUpgradeConfigurationReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*UpdateUpgradeConfigurationOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for updateUpgradeConfiguration: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
