// Code generated by go-swagger; DO NOT EDIT.

package spaces

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCreateSpaceLogoParams creates a new CreateSpaceLogoParams object
// with the default values initialized.
func NewCreateSpaceLogoParams() *CreateSpaceLogoParams {
	var ()
	return &CreateSpaceLogoParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateSpaceLogoParamsWithTimeout creates a new CreateSpaceLogoParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateSpaceLogoParamsWithTimeout(timeout time.Duration) *CreateSpaceLogoParams {
	var ()
	return &CreateSpaceLogoParams{

		timeout: timeout,
	}
}

// NewCreateSpaceLogoParamsWithContext creates a new CreateSpaceLogoParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateSpaceLogoParamsWithContext(ctx context.Context) *CreateSpaceLogoParams {
	var ()
	return &CreateSpaceLogoParams{

		Context: ctx,
	}
}

// NewCreateSpaceLogoParamsWithHTTPClient creates a new CreateSpaceLogoParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateSpaceLogoParamsWithHTTPClient(client *http.Client) *CreateSpaceLogoParams {
	var ()
	return &CreateSpaceLogoParams{
		HTTPClient: client,
	}
}

/*CreateSpaceLogoParams contains all the parameters to send to the API endpoint
for the create space logo operation typically these are written to a http.Request
*/
type CreateSpaceLogoParams struct {

	/*ID
	  ID of the resource

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create space logo params
func (o *CreateSpaceLogoParams) WithTimeout(timeout time.Duration) *CreateSpaceLogoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create space logo params
func (o *CreateSpaceLogoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create space logo params
func (o *CreateSpaceLogoParams) WithContext(ctx context.Context) *CreateSpaceLogoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create space logo params
func (o *CreateSpaceLogoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create space logo params
func (o *CreateSpaceLogoParams) WithHTTPClient(client *http.Client) *CreateSpaceLogoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create space logo params
func (o *CreateSpaceLogoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the create space logo params
func (o *CreateSpaceLogoParams) WithID(id string) *CreateSpaceLogoParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the create space logo params
func (o *CreateSpaceLogoParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *CreateSpaceLogoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
