// Code generated by go-swagger; DO NOT EDIT.

package spaces

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteSpaceParams creates a new DeleteSpaceParams object
// with the default values initialized.
func NewDeleteSpaceParams() *DeleteSpaceParams {
	var ()
	return &DeleteSpaceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteSpaceParamsWithTimeout creates a new DeleteSpaceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteSpaceParamsWithTimeout(timeout time.Duration) *DeleteSpaceParams {
	var ()
	return &DeleteSpaceParams{

		timeout: timeout,
	}
}

// NewDeleteSpaceParamsWithContext creates a new DeleteSpaceParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteSpaceParamsWithContext(ctx context.Context) *DeleteSpaceParams {
	var ()
	return &DeleteSpaceParams{

		Context: ctx,
	}
}

// NewDeleteSpaceParamsWithHTTPClient creates a new DeleteSpaceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteSpaceParamsWithHTTPClient(client *http.Client) *DeleteSpaceParams {
	var ()
	return &DeleteSpaceParams{
		HTTPClient: client,
	}
}

/*DeleteSpaceParams contains all the parameters to send to the API endpoint
for the delete space operation typically these are written to a http.Request
*/
type DeleteSpaceParams struct {

	/*ID
	  ID of the resource

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete space params
func (o *DeleteSpaceParams) WithTimeout(timeout time.Duration) *DeleteSpaceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete space params
func (o *DeleteSpaceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete space params
func (o *DeleteSpaceParams) WithContext(ctx context.Context) *DeleteSpaceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete space params
func (o *DeleteSpaceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete space params
func (o *DeleteSpaceParams) WithHTTPClient(client *http.Client) *DeleteSpaceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete space params
func (o *DeleteSpaceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete space params
func (o *DeleteSpaceParams) WithID(id string) *DeleteSpaceParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete space params
func (o *DeleteSpaceParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteSpaceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
