// Code generated by go-swagger; DO NOT EDIT.

package spaces

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// GetSpaceByIDReader is a Reader for the GetSpaceByID structure.
type GetSpaceByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSpaceByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSpaceByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetSpaceByIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetSpaceByIDOK creates a GetSpaceByIDOK with default headers values
func NewGetSpaceByIDOK() *GetSpaceByIDOK {
	return &GetSpaceByIDOK{}
}

/*GetSpaceByIDOK handles this case with default header values.

Load SpaceResource by ID
*/
type GetSpaceByIDOK struct {
	Payload *models.SpaceResource
}

func (o *GetSpaceByIDOK) Error() string {
	return fmt.Sprintf("[GET /api/spaces/{id}][%d] getSpaceByIdOK  %+v", 200, o.Payload)
}

func (o *GetSpaceByIDOK) GetPayload() *models.SpaceResource {
	return o.Payload
}

func (o *GetSpaceByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SpaceResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSpaceByIDBadRequest creates a GetSpaceByIDBadRequest with default headers values
func NewGetSpaceByIDBadRequest() *GetSpaceByIDBadRequest {
	return &GetSpaceByIDBadRequest{}
}

/*GetSpaceByIDBadRequest handles this case with default header values.

No id parameter was provided.
*/
type GetSpaceByIDBadRequest struct {
}

func (o *GetSpaceByIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/spaces/{id}][%d] getSpaceByIdBadRequest ", 400)
}

func (o *GetSpaceByIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
