// Code generated by go-swagger; DO NOT EDIT.

package runbooks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// CreateRunbookRunForPublishedRunbookCreateSpacesReader is a Reader for the CreateRunbookRunForPublishedRunbookCreateSpaces structure.
type CreateRunbookRunForPublishedRunbookCreateSpacesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateRunbookRunForPublishedRunbookCreateSpacesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateRunbookRunForPublishedRunbookCreateSpacesCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateRunbookRunForPublishedRunbookCreateSpacesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateRunbookRunForPublishedRunbookCreateSpacesCreated creates a CreateRunbookRunForPublishedRunbookCreateSpacesCreated with default headers values
func NewCreateRunbookRunForPublishedRunbookCreateSpacesCreated() *CreateRunbookRunForPublishedRunbookCreateSpacesCreated {
	return &CreateRunbookRunForPublishedRunbookCreateSpacesCreated{}
}

/*CreateRunbookRunForPublishedRunbookCreateSpacesCreated handles this case with default header values.

RunbookRunResource[] resource returned
*/
type CreateRunbookRunForPublishedRunbookCreateSpacesCreated struct {
	Payload []*models.RunbookRunResource
}

func (o *CreateRunbookRunForPublishedRunbookCreateSpacesCreated) Error() string {
	return fmt.Sprintf("[POST /api/{baseSpaceId}/runbooks/{id}/run][%d] createRunbookRunForPublishedRunbookCreateSpacesCreated  %+v", 201, o.Payload)
}

func (o *CreateRunbookRunForPublishedRunbookCreateSpacesCreated) GetPayload() []*models.RunbookRunResource {
	return o.Payload
}

func (o *CreateRunbookRunForPublishedRunbookCreateSpacesCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateRunbookRunForPublishedRunbookCreateSpacesBadRequest creates a CreateRunbookRunForPublishedRunbookCreateSpacesBadRequest with default headers values
func NewCreateRunbookRunForPublishedRunbookCreateSpacesBadRequest() *CreateRunbookRunForPublishedRunbookCreateSpacesBadRequest {
	return &CreateRunbookRunForPublishedRunbookCreateSpacesBadRequest{}
}

/*CreateRunbookRunForPublishedRunbookCreateSpacesBadRequest handles this case with default header values.

No id parameter was provided.
No request body was supplied.
Runbook has no published snapshot.
RunbookRun creation failed.
RunbookRun Schedule is invalid.
*/
type CreateRunbookRunForPublishedRunbookCreateSpacesBadRequest struct {
}

func (o *CreateRunbookRunForPublishedRunbookCreateSpacesBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/{baseSpaceId}/runbooks/{id}/run][%d] createRunbookRunForPublishedRunbookCreateSpacesBadRequest ", 400)
}

func (o *CreateRunbookRunForPublishedRunbookCreateSpacesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
