// Code generated by go-swagger; DO NOT EDIT.

package runbooks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCreateRunbookRunForPublishedRunbookCreateSpacesParams creates a new CreateRunbookRunForPublishedRunbookCreateSpacesParams object
// with the default values initialized.
func NewCreateRunbookRunForPublishedRunbookCreateSpacesParams() *CreateRunbookRunForPublishedRunbookCreateSpacesParams {
	var ()
	return &CreateRunbookRunForPublishedRunbookCreateSpacesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateRunbookRunForPublishedRunbookCreateSpacesParamsWithTimeout creates a new CreateRunbookRunForPublishedRunbookCreateSpacesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateRunbookRunForPublishedRunbookCreateSpacesParamsWithTimeout(timeout time.Duration) *CreateRunbookRunForPublishedRunbookCreateSpacesParams {
	var ()
	return &CreateRunbookRunForPublishedRunbookCreateSpacesParams{

		timeout: timeout,
	}
}

// NewCreateRunbookRunForPublishedRunbookCreateSpacesParamsWithContext creates a new CreateRunbookRunForPublishedRunbookCreateSpacesParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateRunbookRunForPublishedRunbookCreateSpacesParamsWithContext(ctx context.Context) *CreateRunbookRunForPublishedRunbookCreateSpacesParams {
	var ()
	return &CreateRunbookRunForPublishedRunbookCreateSpacesParams{

		Context: ctx,
	}
}

// NewCreateRunbookRunForPublishedRunbookCreateSpacesParamsWithHTTPClient creates a new CreateRunbookRunForPublishedRunbookCreateSpacesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateRunbookRunForPublishedRunbookCreateSpacesParamsWithHTTPClient(client *http.Client) *CreateRunbookRunForPublishedRunbookCreateSpacesParams {
	var ()
	return &CreateRunbookRunForPublishedRunbookCreateSpacesParams{
		HTTPClient: client,
	}
}

/*CreateRunbookRunForPublishedRunbookCreateSpacesParams contains all the parameters to send to the API endpoint
for the create runbook run for published runbook create spaces operation typically these are written to a http.Request
*/
type CreateRunbookRunForPublishedRunbookCreateSpacesParams struct {

	/*BaseSpaceID
	  ID of the space

	*/
	BaseSpaceID string
	/*ID
	  ID of the resource

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create runbook run for published runbook create spaces params
func (o *CreateRunbookRunForPublishedRunbookCreateSpacesParams) WithTimeout(timeout time.Duration) *CreateRunbookRunForPublishedRunbookCreateSpacesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create runbook run for published runbook create spaces params
func (o *CreateRunbookRunForPublishedRunbookCreateSpacesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create runbook run for published runbook create spaces params
func (o *CreateRunbookRunForPublishedRunbookCreateSpacesParams) WithContext(ctx context.Context) *CreateRunbookRunForPublishedRunbookCreateSpacesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create runbook run for published runbook create spaces params
func (o *CreateRunbookRunForPublishedRunbookCreateSpacesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create runbook run for published runbook create spaces params
func (o *CreateRunbookRunForPublishedRunbookCreateSpacesParams) WithHTTPClient(client *http.Client) *CreateRunbookRunForPublishedRunbookCreateSpacesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create runbook run for published runbook create spaces params
func (o *CreateRunbookRunForPublishedRunbookCreateSpacesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBaseSpaceID adds the baseSpaceID to the create runbook run for published runbook create spaces params
func (o *CreateRunbookRunForPublishedRunbookCreateSpacesParams) WithBaseSpaceID(baseSpaceID string) *CreateRunbookRunForPublishedRunbookCreateSpacesParams {
	o.SetBaseSpaceID(baseSpaceID)
	return o
}

// SetBaseSpaceID adds the baseSpaceId to the create runbook run for published runbook create spaces params
func (o *CreateRunbookRunForPublishedRunbookCreateSpacesParams) SetBaseSpaceID(baseSpaceID string) {
	o.BaseSpaceID = baseSpaceID
}

// WithID adds the id to the create runbook run for published runbook create spaces params
func (o *CreateRunbookRunForPublishedRunbookCreateSpacesParams) WithID(id string) *CreateRunbookRunForPublishedRunbookCreateSpacesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the create runbook run for published runbook create spaces params
func (o *CreateRunbookRunForPublishedRunbookCreateSpacesParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *CreateRunbookRunForPublishedRunbookCreateSpacesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param baseSpaceId
	if err := r.SetPathParam("baseSpaceId", o.BaseSpaceID); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
