// Code generated by go-swagger; DO NOT EDIT.

package runbooks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// GetRunbookEnvironmentsReader is a Reader for the GetRunbookEnvironments structure.
type GetRunbookEnvironmentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRunbookEnvironmentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetRunbookEnvironmentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetRunbookEnvironmentsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetRunbookEnvironmentsOK creates a GetRunbookEnvironmentsOK with default headers values
func NewGetRunbookEnvironmentsOK() *GetRunbookEnvironmentsOK {
	return &GetRunbookEnvironmentsOK{}
}

/*GetRunbookEnvironmentsOK handles this case with default header values.

List_of_EnvironmentResource resource returned
*/
type GetRunbookEnvironmentsOK struct {
	Payload []*models.EnvironmentResource
}

func (o *GetRunbookEnvironmentsOK) Error() string {
	return fmt.Sprintf("[GET /api/runbooks/{id}/environments][%d] getRunbookEnvironmentsOK  %+v", 200, o.Payload)
}

func (o *GetRunbookEnvironmentsOK) GetPayload() []*models.EnvironmentResource {
	return o.Payload
}

func (o *GetRunbookEnvironmentsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRunbookEnvironmentsBadRequest creates a GetRunbookEnvironmentsBadRequest with default headers values
func NewGetRunbookEnvironmentsBadRequest() *GetRunbookEnvironmentsBadRequest {
	return &GetRunbookEnvironmentsBadRequest{}
}

/*GetRunbookEnvironmentsBadRequest handles this case with default header values.

No id parameter was provided.
*/
type GetRunbookEnvironmentsBadRequest struct {
}

func (o *GetRunbookEnvironmentsBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/runbooks/{id}/environments][%d] getRunbookEnvironmentsBadRequest ", 400)
}

func (o *GetRunbookEnvironmentsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
