// Code generated by go-swagger; DO NOT EDIT.

package runbooks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetRunbookRunTemplateForRunbookParams creates a new GetRunbookRunTemplateForRunbookParams object
// with the default values initialized.
func NewGetRunbookRunTemplateForRunbookParams() *GetRunbookRunTemplateForRunbookParams {
	var ()
	return &GetRunbookRunTemplateForRunbookParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRunbookRunTemplateForRunbookParamsWithTimeout creates a new GetRunbookRunTemplateForRunbookParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRunbookRunTemplateForRunbookParamsWithTimeout(timeout time.Duration) *GetRunbookRunTemplateForRunbookParams {
	var ()
	return &GetRunbookRunTemplateForRunbookParams{

		timeout: timeout,
	}
}

// NewGetRunbookRunTemplateForRunbookParamsWithContext creates a new GetRunbookRunTemplateForRunbookParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRunbookRunTemplateForRunbookParamsWithContext(ctx context.Context) *GetRunbookRunTemplateForRunbookParams {
	var ()
	return &GetRunbookRunTemplateForRunbookParams{

		Context: ctx,
	}
}

// NewGetRunbookRunTemplateForRunbookParamsWithHTTPClient creates a new GetRunbookRunTemplateForRunbookParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRunbookRunTemplateForRunbookParamsWithHTTPClient(client *http.Client) *GetRunbookRunTemplateForRunbookParams {
	var ()
	return &GetRunbookRunTemplateForRunbookParams{
		HTTPClient: client,
	}
}

/*GetRunbookRunTemplateForRunbookParams contains all the parameters to send to the API endpoint
for the get runbook run template for runbook operation typically these are written to a http.Request
*/
type GetRunbookRunTemplateForRunbookParams struct {

	/*ID
	  ID of the resource

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get runbook run template for runbook params
func (o *GetRunbookRunTemplateForRunbookParams) WithTimeout(timeout time.Duration) *GetRunbookRunTemplateForRunbookParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get runbook run template for runbook params
func (o *GetRunbookRunTemplateForRunbookParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get runbook run template for runbook params
func (o *GetRunbookRunTemplateForRunbookParams) WithContext(ctx context.Context) *GetRunbookRunTemplateForRunbookParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get runbook run template for runbook params
func (o *GetRunbookRunTemplateForRunbookParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get runbook run template for runbook params
func (o *GetRunbookRunTemplateForRunbookParams) WithHTTPClient(client *http.Client) *GetRunbookRunTemplateForRunbookParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get runbook run template for runbook params
func (o *GetRunbookRunTemplateForRunbookParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get runbook run template for runbook params
func (o *GetRunbookRunTemplateForRunbookParams) WithID(id string) *GetRunbookRunTemplateForRunbookParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get runbook run template for runbook params
func (o *GetRunbookRunTemplateForRunbookParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetRunbookRunTemplateForRunbookParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
