// Code generated by go-swagger; DO NOT EDIT.

package build_information

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteBuildInformationDeleteByIdsSpacesReader is a Reader for the DeleteBuildInformationDeleteByIdsSpaces structure.
type DeleteBuildInformationDeleteByIdsSpacesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteBuildInformationDeleteByIdsSpacesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteBuildInformationDeleteByIdsSpacesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteBuildInformationDeleteByIdsSpacesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteBuildInformationDeleteByIdsSpacesOK creates a DeleteBuildInformationDeleteByIdsSpacesOK with default headers values
func NewDeleteBuildInformationDeleteByIdsSpacesOK() *DeleteBuildInformationDeleteByIdsSpacesOK {
	return &DeleteBuildInformationDeleteByIdsSpacesOK{}
}

/*DeleteBuildInformationDeleteByIdsSpacesOK handles this case with default header values.

OK
*/
type DeleteBuildInformationDeleteByIdsSpacesOK struct {
}

func (o *DeleteBuildInformationDeleteByIdsSpacesOK) Error() string {
	return fmt.Sprintf("[DELETE /api/{baseSpaceId}/build-information/bulk][%d] deleteBuildInformationDeleteByIdsSpacesOK ", 200)
}

func (o *DeleteBuildInformationDeleteByIdsSpacesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteBuildInformationDeleteByIdsSpacesBadRequest creates a DeleteBuildInformationDeleteByIdsSpacesBadRequest with default headers values
func NewDeleteBuildInformationDeleteByIdsSpacesBadRequest() *DeleteBuildInformationDeleteByIdsSpacesBadRequest {
	return &DeleteBuildInformationDeleteByIdsSpacesBadRequest{}
}

/*DeleteBuildInformationDeleteByIdsSpacesBadRequest handles this case with default header values.

No ids parameter was provided.
*/
type DeleteBuildInformationDeleteByIdsSpacesBadRequest struct {
}

func (o *DeleteBuildInformationDeleteByIdsSpacesBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /api/{baseSpaceId}/build-information/bulk][%d] deleteBuildInformationDeleteByIdsSpacesBadRequest ", 400)
}

func (o *DeleteBuildInformationDeleteByIdsSpacesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
