// Code generated by go-swagger; DO NOT EDIT.

package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// IndexDeploymentTargetTasksSpacesReader is a Reader for the IndexDeploymentTargetTasksSpaces structure.
type IndexDeploymentTargetTasksSpacesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IndexDeploymentTargetTasksSpacesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewIndexDeploymentTargetTasksSpacesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewIndexDeploymentTargetTasksSpacesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewIndexDeploymentTargetTasksSpacesOK creates a IndexDeploymentTargetTasksSpacesOK with default headers values
func NewIndexDeploymentTargetTasksSpacesOK() *IndexDeploymentTargetTasksSpacesOK {
	return &IndexDeploymentTargetTasksSpacesOK{}
}

/*IndexDeploymentTargetTasksSpacesOK handles this case with default header values.

ResourceCollection_of_TaskResource resource returned
*/
type IndexDeploymentTargetTasksSpacesOK struct {
	Payload *models.ResourceCollectionOfTaskResource
}

func (o *IndexDeploymentTargetTasksSpacesOK) Error() string {
	return fmt.Sprintf("[GET /api/{baseSpaceId}/machines/{id}/tasks][%d] indexDeploymentTargetTasksSpacesOK  %+v", 200, o.Payload)
}

func (o *IndexDeploymentTargetTasksSpacesOK) GetPayload() *models.ResourceCollectionOfTaskResource {
	return o.Payload
}

func (o *IndexDeploymentTargetTasksSpacesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResourceCollectionOfTaskResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIndexDeploymentTargetTasksSpacesBadRequest creates a IndexDeploymentTargetTasksSpacesBadRequest with default headers values
func NewIndexDeploymentTargetTasksSpacesBadRequest() *IndexDeploymentTargetTasksSpacesBadRequest {
	return &IndexDeploymentTargetTasksSpacesBadRequest{}
}

/*IndexDeploymentTargetTasksSpacesBadRequest handles this case with default header values.

No id parameter was provided.
*/
type IndexDeploymentTargetTasksSpacesBadRequest struct {
}

func (o *IndexDeploymentTargetTasksSpacesBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/{baseSpaceId}/machines/{id}/tasks][%d] indexDeploymentTargetTasksSpacesBadRequest ", 400)
}

func (o *IndexDeploymentTargetTasksSpacesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
