// Code generated by go-swagger; DO NOT EDIT.

package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListAllDeploymentTargetsSpacesParams creates a new ListAllDeploymentTargetsSpacesParams object
// with the default values initialized.
func NewListAllDeploymentTargetsSpacesParams() *ListAllDeploymentTargetsSpacesParams {
	var ()
	return &ListAllDeploymentTargetsSpacesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListAllDeploymentTargetsSpacesParamsWithTimeout creates a new ListAllDeploymentTargetsSpacesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListAllDeploymentTargetsSpacesParamsWithTimeout(timeout time.Duration) *ListAllDeploymentTargetsSpacesParams {
	var ()
	return &ListAllDeploymentTargetsSpacesParams{

		timeout: timeout,
	}
}

// NewListAllDeploymentTargetsSpacesParamsWithContext creates a new ListAllDeploymentTargetsSpacesParams object
// with the default values initialized, and the ability to set a context for a request
func NewListAllDeploymentTargetsSpacesParamsWithContext(ctx context.Context) *ListAllDeploymentTargetsSpacesParams {
	var ()
	return &ListAllDeploymentTargetsSpacesParams{

		Context: ctx,
	}
}

// NewListAllDeploymentTargetsSpacesParamsWithHTTPClient creates a new ListAllDeploymentTargetsSpacesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListAllDeploymentTargetsSpacesParamsWithHTTPClient(client *http.Client) *ListAllDeploymentTargetsSpacesParams {
	var ()
	return &ListAllDeploymentTargetsSpacesParams{
		HTTPClient: client,
	}
}

/*ListAllDeploymentTargetsSpacesParams contains all the parameters to send to the API endpoint
for the list all deployment targets spaces operation typically these are written to a http.Request
*/
type ListAllDeploymentTargetsSpacesParams struct {

	/*BaseSpaceID
	  ID of the space

	*/
	BaseSpaceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list all deployment targets spaces params
func (o *ListAllDeploymentTargetsSpacesParams) WithTimeout(timeout time.Duration) *ListAllDeploymentTargetsSpacesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list all deployment targets spaces params
func (o *ListAllDeploymentTargetsSpacesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list all deployment targets spaces params
func (o *ListAllDeploymentTargetsSpacesParams) WithContext(ctx context.Context) *ListAllDeploymentTargetsSpacesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list all deployment targets spaces params
func (o *ListAllDeploymentTargetsSpacesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list all deployment targets spaces params
func (o *ListAllDeploymentTargetsSpacesParams) WithHTTPClient(client *http.Client) *ListAllDeploymentTargetsSpacesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list all deployment targets spaces params
func (o *ListAllDeploymentTargetsSpacesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBaseSpaceID adds the baseSpaceID to the list all deployment targets spaces params
func (o *ListAllDeploymentTargetsSpacesParams) WithBaseSpaceID(baseSpaceID string) *ListAllDeploymentTargetsSpacesParams {
	o.SetBaseSpaceID(baseSpaceID)
	return o
}

// SetBaseSpaceID adds the baseSpaceId to the list all deployment targets spaces params
func (o *ListAllDeploymentTargetsSpacesParams) SetBaseSpaceID(baseSpaceID string) {
	o.BaseSpaceID = baseSpaceID
}

// WriteToRequest writes these params to a swagger request
func (o *ListAllDeploymentTargetsSpacesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param baseSpaceId
	if err := r.SetPathParam("baseSpaceId", o.BaseSpaceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
