// Code generated by go-swagger; DO NOT EDIT.

package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// GetProjectByIDOrSlugReader is a Reader for the GetProjectByIDOrSlug structure.
type GetProjectByIDOrSlugReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProjectByIDOrSlugReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetProjectByIDOrSlugOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetProjectByIDOrSlugBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetProjectByIDOrSlugOK creates a GetProjectByIDOrSlugOK with default headers values
func NewGetProjectByIDOrSlugOK() *GetProjectByIDOrSlugOK {
	return &GetProjectByIDOrSlugOK{}
}

/*GetProjectByIDOrSlugOK handles this case with default header values.

Load ProjectResource by ID or slug
*/
type GetProjectByIDOrSlugOK struct {
	Payload *models.ProjectResource
}

func (o *GetProjectByIDOrSlugOK) Error() string {
	return fmt.Sprintf("[GET /api/projects/{id}][%d] getProjectByIdOrSlugOK  %+v", 200, o.Payload)
}

func (o *GetProjectByIDOrSlugOK) GetPayload() *models.ProjectResource {
	return o.Payload
}

func (o *GetProjectByIDOrSlugOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProjectResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProjectByIDOrSlugBadRequest creates a GetProjectByIDOrSlugBadRequest with default headers values
func NewGetProjectByIDOrSlugBadRequest() *GetProjectByIDOrSlugBadRequest {
	return &GetProjectByIDOrSlugBadRequest{}
}

/*GetProjectByIDOrSlugBadRequest handles this case with default header values.

No id parameter was provided.
*/
type GetProjectByIDOrSlugBadRequest struct {
}

func (o *GetProjectByIDOrSlugBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/projects/{id}][%d] getProjectByIdOrSlugBadRequest ", 400)
}

func (o *GetProjectByIDOrSlugBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
