// Code generated by go-swagger; DO NOT EDIT.

package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetProjectLogoParams creates a new GetProjectLogoParams object
// with the default values initialized.
func NewGetProjectLogoParams() *GetProjectLogoParams {
	var ()
	return &GetProjectLogoParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetProjectLogoParamsWithTimeout creates a new GetProjectLogoParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetProjectLogoParamsWithTimeout(timeout time.Duration) *GetProjectLogoParams {
	var ()
	return &GetProjectLogoParams{

		timeout: timeout,
	}
}

// NewGetProjectLogoParamsWithContext creates a new GetProjectLogoParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetProjectLogoParamsWithContext(ctx context.Context) *GetProjectLogoParams {
	var ()
	return &GetProjectLogoParams{

		Context: ctx,
	}
}

// NewGetProjectLogoParamsWithHTTPClient creates a new GetProjectLogoParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetProjectLogoParamsWithHTTPClient(client *http.Client) *GetProjectLogoParams {
	var ()
	return &GetProjectLogoParams{
		HTTPClient: client,
	}
}

/*GetProjectLogoParams contains all the parameters to send to the API endpoint
for the get project logo operation typically these are written to a http.Request
*/
type GetProjectLogoParams struct {

	/*ID
	  ID of the resource

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get project logo params
func (o *GetProjectLogoParams) WithTimeout(timeout time.Duration) *GetProjectLogoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get project logo params
func (o *GetProjectLogoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get project logo params
func (o *GetProjectLogoParams) WithContext(ctx context.Context) *GetProjectLogoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get project logo params
func (o *GetProjectLogoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get project logo params
func (o *GetProjectLogoParams) WithHTTPClient(client *http.Client) *GetProjectLogoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get project logo params
func (o *GetProjectLogoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get project logo params
func (o *GetProjectLogoParams) WithID(id string) *GetProjectLogoParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get project logo params
func (o *GetProjectLogoParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetProjectLogoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
