// Code generated by go-swagger; DO NOT EDIT.

package project_groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// CreateProjectGroupReader is a Reader for the CreateProjectGroup structure.
type CreateProjectGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateProjectGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateProjectGroupCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateProjectGroupBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateProjectGroupCreated creates a CreateProjectGroupCreated with default headers values
func NewCreateProjectGroupCreated() *CreateProjectGroupCreated {
	return &CreateProjectGroupCreated{}
}

/*CreateProjectGroupCreated handles this case with default header values.

ProjectGroupResource Created
*/
type CreateProjectGroupCreated struct {
	Payload *models.ProjectGroupResource
}

func (o *CreateProjectGroupCreated) Error() string {
	return fmt.Sprintf("[POST /api/projectgroups][%d] createProjectGroupCreated  %+v", 201, o.Payload)
}

func (o *CreateProjectGroupCreated) GetPayload() *models.ProjectGroupResource {
	return o.Payload
}

func (o *CreateProjectGroupCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProjectGroupResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateProjectGroupBadRequest creates a CreateProjectGroupBadRequest with default headers values
func NewCreateProjectGroupBadRequest() *CreateProjectGroupBadRequest {
	return &CreateProjectGroupBadRequest{}
}

/*CreateProjectGroupBadRequest handles this case with default header values.

Model validation failed.
No request body was supplied.
*/
type CreateProjectGroupBadRequest struct {
}

func (o *CreateProjectGroupBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/projectgroups][%d] createProjectGroupBadRequest ", 400)
}

func (o *CreateProjectGroupBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
