// Code generated by go-swagger; DO NOT EDIT.

package project_groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteProjectGroupSpacesParams creates a new DeleteProjectGroupSpacesParams object
// with the default values initialized.
func NewDeleteProjectGroupSpacesParams() *DeleteProjectGroupSpacesParams {
	var ()
	return &DeleteProjectGroupSpacesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteProjectGroupSpacesParamsWithTimeout creates a new DeleteProjectGroupSpacesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteProjectGroupSpacesParamsWithTimeout(timeout time.Duration) *DeleteProjectGroupSpacesParams {
	var ()
	return &DeleteProjectGroupSpacesParams{

		timeout: timeout,
	}
}

// NewDeleteProjectGroupSpacesParamsWithContext creates a new DeleteProjectGroupSpacesParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteProjectGroupSpacesParamsWithContext(ctx context.Context) *DeleteProjectGroupSpacesParams {
	var ()
	return &DeleteProjectGroupSpacesParams{

		Context: ctx,
	}
}

// NewDeleteProjectGroupSpacesParamsWithHTTPClient creates a new DeleteProjectGroupSpacesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteProjectGroupSpacesParamsWithHTTPClient(client *http.Client) *DeleteProjectGroupSpacesParams {
	var ()
	return &DeleteProjectGroupSpacesParams{
		HTTPClient: client,
	}
}

/*DeleteProjectGroupSpacesParams contains all the parameters to send to the API endpoint
for the delete project group spaces operation typically these are written to a http.Request
*/
type DeleteProjectGroupSpacesParams struct {

	/*BaseSpaceID
	  ID of the space

	*/
	BaseSpaceID string
	/*ID
	  ID of the ProjectGroupResource to delete

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete project group spaces params
func (o *DeleteProjectGroupSpacesParams) WithTimeout(timeout time.Duration) *DeleteProjectGroupSpacesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete project group spaces params
func (o *DeleteProjectGroupSpacesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete project group spaces params
func (o *DeleteProjectGroupSpacesParams) WithContext(ctx context.Context) *DeleteProjectGroupSpacesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete project group spaces params
func (o *DeleteProjectGroupSpacesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete project group spaces params
func (o *DeleteProjectGroupSpacesParams) WithHTTPClient(client *http.Client) *DeleteProjectGroupSpacesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete project group spaces params
func (o *DeleteProjectGroupSpacesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBaseSpaceID adds the baseSpaceID to the delete project group spaces params
func (o *DeleteProjectGroupSpacesParams) WithBaseSpaceID(baseSpaceID string) *DeleteProjectGroupSpacesParams {
	o.SetBaseSpaceID(baseSpaceID)
	return o
}

// SetBaseSpaceID adds the baseSpaceId to the delete project group spaces params
func (o *DeleteProjectGroupSpacesParams) SetBaseSpaceID(baseSpaceID string) {
	o.BaseSpaceID = baseSpaceID
}

// WithID adds the id to the delete project group spaces params
func (o *DeleteProjectGroupSpacesParams) WithID(id string) *DeleteProjectGroupSpacesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete project group spaces params
func (o *DeleteProjectGroupSpacesParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteProjectGroupSpacesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param baseSpaceId
	if err := r.SetPathParam("baseSpaceId", o.BaseSpaceID); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
