// Code generated by go-swagger; DO NOT EDIT.

package worker_pools

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetWorkerPoolsSummaryParams creates a new GetWorkerPoolsSummaryParams object
// with the default values initialized.
func NewGetWorkerPoolsSummaryParams() *GetWorkerPoolsSummaryParams {

	return &GetWorkerPoolsSummaryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetWorkerPoolsSummaryParamsWithTimeout creates a new GetWorkerPoolsSummaryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetWorkerPoolsSummaryParamsWithTimeout(timeout time.Duration) *GetWorkerPoolsSummaryParams {

	return &GetWorkerPoolsSummaryParams{

		timeout: timeout,
	}
}

// NewGetWorkerPoolsSummaryParamsWithContext creates a new GetWorkerPoolsSummaryParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetWorkerPoolsSummaryParamsWithContext(ctx context.Context) *GetWorkerPoolsSummaryParams {

	return &GetWorkerPoolsSummaryParams{

		Context: ctx,
	}
}

// NewGetWorkerPoolsSummaryParamsWithHTTPClient creates a new GetWorkerPoolsSummaryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetWorkerPoolsSummaryParamsWithHTTPClient(client *http.Client) *GetWorkerPoolsSummaryParams {

	return &GetWorkerPoolsSummaryParams{
		HTTPClient: client,
	}
}

/*GetWorkerPoolsSummaryParams contains all the parameters to send to the API endpoint
for the get worker pools summary operation typically these are written to a http.Request
*/
type GetWorkerPoolsSummaryParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get worker pools summary params
func (o *GetWorkerPoolsSummaryParams) WithTimeout(timeout time.Duration) *GetWorkerPoolsSummaryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get worker pools summary params
func (o *GetWorkerPoolsSummaryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get worker pools summary params
func (o *GetWorkerPoolsSummaryParams) WithContext(ctx context.Context) *GetWorkerPoolsSummaryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get worker pools summary params
func (o *GetWorkerPoolsSummaryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get worker pools summary params
func (o *GetWorkerPoolsSummaryParams) WithHTTPClient(client *http.Client) *GetWorkerPoolsSummaryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get worker pools summary params
func (o *GetWorkerPoolsSummaryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetWorkerPoolsSummaryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
