// Code generated by go-swagger; DO NOT EDIT.

package worker_pools

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListAllWorkerPoolsParams creates a new ListAllWorkerPoolsParams object
// with the default values initialized.
func NewListAllWorkerPoolsParams() *ListAllWorkerPoolsParams {

	return &ListAllWorkerPoolsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListAllWorkerPoolsParamsWithTimeout creates a new ListAllWorkerPoolsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListAllWorkerPoolsParamsWithTimeout(timeout time.Duration) *ListAllWorkerPoolsParams {

	return &ListAllWorkerPoolsParams{

		timeout: timeout,
	}
}

// NewListAllWorkerPoolsParamsWithContext creates a new ListAllWorkerPoolsParams object
// with the default values initialized, and the ability to set a context for a request
func NewListAllWorkerPoolsParamsWithContext(ctx context.Context) *ListAllWorkerPoolsParams {

	return &ListAllWorkerPoolsParams{

		Context: ctx,
	}
}

// NewListAllWorkerPoolsParamsWithHTTPClient creates a new ListAllWorkerPoolsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListAllWorkerPoolsParamsWithHTTPClient(client *http.Client) *ListAllWorkerPoolsParams {

	return &ListAllWorkerPoolsParams{
		HTTPClient: client,
	}
}

/*ListAllWorkerPoolsParams contains all the parameters to send to the API endpoint
for the list all worker pools operation typically these are written to a http.Request
*/
type ListAllWorkerPoolsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list all worker pools params
func (o *ListAllWorkerPoolsParams) WithTimeout(timeout time.Duration) *ListAllWorkerPoolsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list all worker pools params
func (o *ListAllWorkerPoolsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list all worker pools params
func (o *ListAllWorkerPoolsParams) WithContext(ctx context.Context) *ListAllWorkerPoolsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list all worker pools params
func (o *ListAllWorkerPoolsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list all worker pools params
func (o *ListAllWorkerPoolsParams) WithHTTPClient(client *http.Client) *ListAllWorkerPoolsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list all worker pools params
func (o *ListAllWorkerPoolsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ListAllWorkerPoolsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
