// Code generated by go-swagger; DO NOT EDIT.

package worker_pools

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// ListAllWorkerPoolsReader is a Reader for the ListAllWorkerPools structure.
type ListAllWorkerPoolsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListAllWorkerPoolsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListAllWorkerPoolsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListAllWorkerPoolsOK creates a ListAllWorkerPoolsOK with default headers values
func NewListAllWorkerPoolsOK() *ListAllWorkerPoolsOK {
	return &ListAllWorkerPoolsOK{}
}

/*ListAllWorkerPoolsOK handles this case with default header values.

Load all WorkerPoolResource
*/
type ListAllWorkerPoolsOK struct {
	Payload []*models.WorkerPoolResource
}

func (o *ListAllWorkerPoolsOK) Error() string {
	return fmt.Sprintf("[GET /api/workerpools/all][%d] listAllWorkerPoolsOK  %+v", 200, o.Payload)
}

func (o *ListAllWorkerPoolsOK) GetPayload() []*models.WorkerPoolResource {
	return o.Payload
}

func (o *ListAllWorkerPoolsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
