// Code generated by go-swagger; DO NOT EDIT.

package tag_sets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// GetTagSetByIDReader is a Reader for the GetTagSetByID structure.
type GetTagSetByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTagSetByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTagSetByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetTagSetByIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetTagSetByIDOK creates a GetTagSetByIDOK with default headers values
func NewGetTagSetByIDOK() *GetTagSetByIDOK {
	return &GetTagSetByIDOK{}
}

/*GetTagSetByIDOK handles this case with default header values.

Load TagSetResource by ID
*/
type GetTagSetByIDOK struct {
	Payload *models.TagSetResource
}

func (o *GetTagSetByIDOK) Error() string {
	return fmt.Sprintf("[GET /api/tagsets/{id}][%d] getTagSetByIdOK  %+v", 200, o.Payload)
}

func (o *GetTagSetByIDOK) GetPayload() *models.TagSetResource {
	return o.Payload
}

func (o *GetTagSetByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TagSetResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTagSetByIDBadRequest creates a GetTagSetByIDBadRequest with default headers values
func NewGetTagSetByIDBadRequest() *GetTagSetByIDBadRequest {
	return &GetTagSetByIDBadRequest{}
}

/*GetTagSetByIDBadRequest handles this case with default header values.

No id parameter was provided.
*/
type GetTagSetByIDBadRequest struct {
}

func (o *GetTagSetByIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/tagsets/{id}][%d] getTagSetByIdBadRequest ", 400)
}

func (o *GetTagSetByIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
