// Code generated by go-swagger; DO NOT EDIT.

package tag_sets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListAllTagSetsParams creates a new ListAllTagSetsParams object
// with the default values initialized.
func NewListAllTagSetsParams() *ListAllTagSetsParams {

	return &ListAllTagSetsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListAllTagSetsParamsWithTimeout creates a new ListAllTagSetsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListAllTagSetsParamsWithTimeout(timeout time.Duration) *ListAllTagSetsParams {

	return &ListAllTagSetsParams{

		timeout: timeout,
	}
}

// NewListAllTagSetsParamsWithContext creates a new ListAllTagSetsParams object
// with the default values initialized, and the ability to set a context for a request
func NewListAllTagSetsParamsWithContext(ctx context.Context) *ListAllTagSetsParams {

	return &ListAllTagSetsParams{

		Context: ctx,
	}
}

// NewListAllTagSetsParamsWithHTTPClient creates a new ListAllTagSetsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListAllTagSetsParamsWithHTTPClient(client *http.Client) *ListAllTagSetsParams {

	return &ListAllTagSetsParams{
		HTTPClient: client,
	}
}

/*ListAllTagSetsParams contains all the parameters to send to the API endpoint
for the list all tag sets operation typically these are written to a http.Request
*/
type ListAllTagSetsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list all tag sets params
func (o *ListAllTagSetsParams) WithTimeout(timeout time.Duration) *ListAllTagSetsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list all tag sets params
func (o *ListAllTagSetsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list all tag sets params
func (o *ListAllTagSetsParams) WithContext(ctx context.Context) *ListAllTagSetsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list all tag sets params
func (o *ListAllTagSetsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list all tag sets params
func (o *ListAllTagSetsParams) WithHTTPClient(client *http.Client) *ListAllTagSetsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list all tag sets params
func (o *ListAllTagSetsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ListAllTagSetsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
