// Code generated by go-swagger; DO NOT EDIT.

package lets_encrypt

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetLetsEncryptHTTPChallengeParams creates a new GetLetsEncryptHTTPChallengeParams object
// with the default values initialized.
func NewGetLetsEncryptHTTPChallengeParams() *GetLetsEncryptHTTPChallengeParams {
	var ()
	return &GetLetsEncryptHTTPChallengeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetLetsEncryptHTTPChallengeParamsWithTimeout creates a new GetLetsEncryptHTTPChallengeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetLetsEncryptHTTPChallengeParamsWithTimeout(timeout time.Duration) *GetLetsEncryptHTTPChallengeParams {
	var ()
	return &GetLetsEncryptHTTPChallengeParams{

		timeout: timeout,
	}
}

// NewGetLetsEncryptHTTPChallengeParamsWithContext creates a new GetLetsEncryptHTTPChallengeParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetLetsEncryptHTTPChallengeParamsWithContext(ctx context.Context) *GetLetsEncryptHTTPChallengeParams {
	var ()
	return &GetLetsEncryptHTTPChallengeParams{

		Context: ctx,
	}
}

// NewGetLetsEncryptHTTPChallengeParamsWithHTTPClient creates a new GetLetsEncryptHTTPChallengeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetLetsEncryptHTTPChallengeParamsWithHTTPClient(client *http.Client) *GetLetsEncryptHTTPChallengeParams {
	var ()
	return &GetLetsEncryptHTTPChallengeParams{
		HTTPClient: client,
	}
}

/*GetLetsEncryptHTTPChallengeParams contains all the parameters to send to the API endpoint
for the get lets encrypt Http challenge operation typically these are written to a http.Request
*/
type GetLetsEncryptHTTPChallengeParams struct {

	/*Token
	  LetsEncrypt response token

	*/
	Token string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get lets encrypt Http challenge params
func (o *GetLetsEncryptHTTPChallengeParams) WithTimeout(timeout time.Duration) *GetLetsEncryptHTTPChallengeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get lets encrypt Http challenge params
func (o *GetLetsEncryptHTTPChallengeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get lets encrypt Http challenge params
func (o *GetLetsEncryptHTTPChallengeParams) WithContext(ctx context.Context) *GetLetsEncryptHTTPChallengeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get lets encrypt Http challenge params
func (o *GetLetsEncryptHTTPChallengeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get lets encrypt Http challenge params
func (o *GetLetsEncryptHTTPChallengeParams) WithHTTPClient(client *http.Client) *GetLetsEncryptHTTPChallengeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get lets encrypt Http challenge params
func (o *GetLetsEncryptHTTPChallengeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithToken adds the token to the get lets encrypt Http challenge params
func (o *GetLetsEncryptHTTPChallengeParams) WithToken(token string) *GetLetsEncryptHTTPChallengeParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the get lets encrypt Http challenge params
func (o *GetLetsEncryptHTTPChallengeParams) SetToken(token string) {
	o.Token = token
}

// WriteToRequest writes these params to a swagger request
func (o *GetLetsEncryptHTTPChallengeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param token
	if err := r.SetPathParam("token", o.Token); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
