// Code generated by go-swagger; DO NOT EDIT.

package user_roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// CreateUserRoleReader is a Reader for the CreateUserRole structure.
type CreateUserRoleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateUserRoleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateUserRoleCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateUserRoleBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateUserRoleCreated creates a CreateUserRoleCreated with default headers values
func NewCreateUserRoleCreated() *CreateUserRoleCreated {
	return &CreateUserRoleCreated{}
}

/*CreateUserRoleCreated handles this case with default header values.

UserRoleResource Created
*/
type CreateUserRoleCreated struct {
	Payload *models.UserRoleResource
}

func (o *CreateUserRoleCreated) Error() string {
	return fmt.Sprintf("[POST /api/userroles][%d] createUserRoleCreated  %+v", 201, o.Payload)
}

func (o *CreateUserRoleCreated) GetPayload() *models.UserRoleResource {
	return o.Payload
}

func (o *CreateUserRoleCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UserRoleResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateUserRoleBadRequest creates a CreateUserRoleBadRequest with default headers values
func NewCreateUserRoleBadRequest() *CreateUserRoleBadRequest {
	return &CreateUserRoleBadRequest{}
}

/*CreateUserRoleBadRequest handles this case with default header values.

Model validation failed.
No request body was supplied.
*/
type CreateUserRoleBadRequest struct {
}

func (o *CreateUserRoleBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/userroles][%d] createUserRoleBadRequest ", 400)
}

func (o *CreateUserRoleBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
