// Code generated by go-swagger; DO NOT EDIT.

package project_triggers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"models"
)

// NewUpdateProjectTriggerParams creates a new UpdateProjectTriggerParams object
// with the default values initialized.
func NewUpdateProjectTriggerParams() *UpdateProjectTriggerParams {
	var ()
	return &UpdateProjectTriggerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateProjectTriggerParamsWithTimeout creates a new UpdateProjectTriggerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateProjectTriggerParamsWithTimeout(timeout time.Duration) *UpdateProjectTriggerParams {
	var ()
	return &UpdateProjectTriggerParams{

		timeout: timeout,
	}
}

// NewUpdateProjectTriggerParamsWithContext creates a new UpdateProjectTriggerParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateProjectTriggerParamsWithContext(ctx context.Context) *UpdateProjectTriggerParams {
	var ()
	return &UpdateProjectTriggerParams{

		Context: ctx,
	}
}

// NewUpdateProjectTriggerParamsWithHTTPClient creates a new UpdateProjectTriggerParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateProjectTriggerParamsWithHTTPClient(client *http.Client) *UpdateProjectTriggerParams {
	var ()
	return &UpdateProjectTriggerParams{
		HTTPClient: client,
	}
}

/*UpdateProjectTriggerParams contains all the parameters to send to the API endpoint
for the update project trigger operation typically these are written to a http.Request
*/
type UpdateProjectTriggerParams struct {

	/*ProjectTriggerResource
	  The ProjectTriggerResource resource to create

	*/
	ProjectTriggerResource *models.ProjectTriggerResource
	/*ID
	  ID of the ProjectTriggerResource to modify

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update project trigger params
func (o *UpdateProjectTriggerParams) WithTimeout(timeout time.Duration) *UpdateProjectTriggerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update project trigger params
func (o *UpdateProjectTriggerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update project trigger params
func (o *UpdateProjectTriggerParams) WithContext(ctx context.Context) *UpdateProjectTriggerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update project trigger params
func (o *UpdateProjectTriggerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update project trigger params
func (o *UpdateProjectTriggerParams) WithHTTPClient(client *http.Client) *UpdateProjectTriggerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update project trigger params
func (o *UpdateProjectTriggerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProjectTriggerResource adds the projectTriggerResource to the update project trigger params
func (o *UpdateProjectTriggerParams) WithProjectTriggerResource(projectTriggerResource *models.ProjectTriggerResource) *UpdateProjectTriggerParams {
	o.SetProjectTriggerResource(projectTriggerResource)
	return o
}

// SetProjectTriggerResource adds the projectTriggerResource to the update project trigger params
func (o *UpdateProjectTriggerParams) SetProjectTriggerResource(projectTriggerResource *models.ProjectTriggerResource) {
	o.ProjectTriggerResource = projectTriggerResource
}

// WithID adds the id to the update project trigger params
func (o *UpdateProjectTriggerParams) WithID(id string) *UpdateProjectTriggerParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update project trigger params
func (o *UpdateProjectTriggerParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateProjectTriggerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ProjectTriggerResource != nil {
		if err := r.SetBodyParam(o.ProjectTriggerResource); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
