// Code generated by go-swagger; DO NOT EDIT.

package workers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetWorkerOperatingSystemShellNameListAllSpacesReader is a Reader for the GetWorkerOperatingSystemShellNameListAllSpaces structure.
type GetWorkerOperatingSystemShellNameListAllSpacesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetWorkerOperatingSystemShellNameListAllSpacesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetWorkerOperatingSystemShellNameListAllSpacesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetWorkerOperatingSystemShellNameListAllSpacesOK creates a GetWorkerOperatingSystemShellNameListAllSpacesOK with default headers values
func NewGetWorkerOperatingSystemShellNameListAllSpacesOK() *GetWorkerOperatingSystemShellNameListAllSpacesOK {
	return &GetWorkerOperatingSystemShellNameListAllSpacesOK{}
}

/*GetWorkerOperatingSystemShellNameListAllSpacesOK handles this case with default header values.

IEnumerable_of_String resource returned
*/
type GetWorkerOperatingSystemShellNameListAllSpacesOK struct {
	Payload []string
}

func (o *GetWorkerOperatingSystemShellNameListAllSpacesOK) Error() string {
	return fmt.Sprintf("[GET /api/{baseSpaceId}/workers/operatingsystem/shells/all][%d] getWorkerOperatingSystemShellNameListAllSpacesOK  %+v", 200, o.Payload)
}

func (o *GetWorkerOperatingSystemShellNameListAllSpacesOK) GetPayload() []string {
	return o.Payload
}

func (o *GetWorkerOperatingSystemShellNameListAllSpacesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
