// Code generated by go-swagger; DO NOT EDIT.

package workers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetWorkerOperatingSystemNamesListAllSpacesParams creates a new GetWorkerOperatingSystemNamesListAllSpacesParams object
// with the default values initialized.
func NewGetWorkerOperatingSystemNamesListAllSpacesParams() *GetWorkerOperatingSystemNamesListAllSpacesParams {
	var ()
	return &GetWorkerOperatingSystemNamesListAllSpacesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetWorkerOperatingSystemNamesListAllSpacesParamsWithTimeout creates a new GetWorkerOperatingSystemNamesListAllSpacesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetWorkerOperatingSystemNamesListAllSpacesParamsWithTimeout(timeout time.Duration) *GetWorkerOperatingSystemNamesListAllSpacesParams {
	var ()
	return &GetWorkerOperatingSystemNamesListAllSpacesParams{

		timeout: timeout,
	}
}

// NewGetWorkerOperatingSystemNamesListAllSpacesParamsWithContext creates a new GetWorkerOperatingSystemNamesListAllSpacesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetWorkerOperatingSystemNamesListAllSpacesParamsWithContext(ctx context.Context) *GetWorkerOperatingSystemNamesListAllSpacesParams {
	var ()
	return &GetWorkerOperatingSystemNamesListAllSpacesParams{

		Context: ctx,
	}
}

// NewGetWorkerOperatingSystemNamesListAllSpacesParamsWithHTTPClient creates a new GetWorkerOperatingSystemNamesListAllSpacesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetWorkerOperatingSystemNamesListAllSpacesParamsWithHTTPClient(client *http.Client) *GetWorkerOperatingSystemNamesListAllSpacesParams {
	var ()
	return &GetWorkerOperatingSystemNamesListAllSpacesParams{
		HTTPClient: client,
	}
}

/*GetWorkerOperatingSystemNamesListAllSpacesParams contains all the parameters to send to the API endpoint
for the get worker operating system names list all spaces operation typically these are written to a http.Request
*/
type GetWorkerOperatingSystemNamesListAllSpacesParams struct {

	/*BaseSpaceID
	  ID of the space

	*/
	BaseSpaceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get worker operating system names list all spaces params
func (o *GetWorkerOperatingSystemNamesListAllSpacesParams) WithTimeout(timeout time.Duration) *GetWorkerOperatingSystemNamesListAllSpacesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get worker operating system names list all spaces params
func (o *GetWorkerOperatingSystemNamesListAllSpacesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get worker operating system names list all spaces params
func (o *GetWorkerOperatingSystemNamesListAllSpacesParams) WithContext(ctx context.Context) *GetWorkerOperatingSystemNamesListAllSpacesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get worker operating system names list all spaces params
func (o *GetWorkerOperatingSystemNamesListAllSpacesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get worker operating system names list all spaces params
func (o *GetWorkerOperatingSystemNamesListAllSpacesParams) WithHTTPClient(client *http.Client) *GetWorkerOperatingSystemNamesListAllSpacesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get worker operating system names list all spaces params
func (o *GetWorkerOperatingSystemNamesListAllSpacesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBaseSpaceID adds the baseSpaceID to the get worker operating system names list all spaces params
func (o *GetWorkerOperatingSystemNamesListAllSpacesParams) WithBaseSpaceID(baseSpaceID string) *GetWorkerOperatingSystemNamesListAllSpacesParams {
	o.SetBaseSpaceID(baseSpaceID)
	return o
}

// SetBaseSpaceID adds the baseSpaceId to the get worker operating system names list all spaces params
func (o *GetWorkerOperatingSystemNamesListAllSpacesParams) SetBaseSpaceID(baseSpaceID string) {
	o.BaseSpaceID = baseSpaceID
}

// WriteToRequest writes these params to a swagger request
func (o *GetWorkerOperatingSystemNamesListAllSpacesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param baseSpaceId
	if err := r.SetPathParam("baseSpaceId", o.BaseSpaceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
