// Code generated by go-swagger; DO NOT EDIT.

package workers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// IndexWorkersSpacesReader is a Reader for the IndexWorkersSpaces structure.
type IndexWorkersSpacesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IndexWorkersSpacesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewIndexWorkersSpacesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewIndexWorkersSpacesOK creates a IndexWorkersSpacesOK with default headers values
func NewIndexWorkersSpacesOK() *IndexWorkersSpacesOK {
	return &IndexWorkersSpacesOK{}
}

/*IndexWorkersSpacesOK handles this case with default header values.

ResourceCollection_of_WorkerResource resource returned
*/
type IndexWorkersSpacesOK struct {
	Payload *models.ResourceCollectionOfWorkerResource
}

func (o *IndexWorkersSpacesOK) Error() string {
	return fmt.Sprintf("[GET /api/{baseSpaceId}/workers][%d] indexWorkersSpacesOK  %+v", 200, o.Payload)
}

func (o *IndexWorkersSpacesOK) GetPayload() *models.ResourceCollectionOfWorkerResource {
	return o.Payload
}

func (o *IndexWorkersSpacesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResourceCollectionOfWorkerResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
