// Code generated by go-swagger; DO NOT EDIT.

package workers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"models"
)

// NewUpdateWorkerSpacesParams creates a new UpdateWorkerSpacesParams object
// with the default values initialized.
func NewUpdateWorkerSpacesParams() *UpdateWorkerSpacesParams {
	var ()
	return &UpdateWorkerSpacesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateWorkerSpacesParamsWithTimeout creates a new UpdateWorkerSpacesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateWorkerSpacesParamsWithTimeout(timeout time.Duration) *UpdateWorkerSpacesParams {
	var ()
	return &UpdateWorkerSpacesParams{

		timeout: timeout,
	}
}

// NewUpdateWorkerSpacesParamsWithContext creates a new UpdateWorkerSpacesParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateWorkerSpacesParamsWithContext(ctx context.Context) *UpdateWorkerSpacesParams {
	var ()
	return &UpdateWorkerSpacesParams{

		Context: ctx,
	}
}

// NewUpdateWorkerSpacesParamsWithHTTPClient creates a new UpdateWorkerSpacesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateWorkerSpacesParamsWithHTTPClient(client *http.Client) *UpdateWorkerSpacesParams {
	var ()
	return &UpdateWorkerSpacesParams{
		HTTPClient: client,
	}
}

/*UpdateWorkerSpacesParams contains all the parameters to send to the API endpoint
for the update worker spaces operation typically these are written to a http.Request
*/
type UpdateWorkerSpacesParams struct {

	/*WorkerResource
	  The WorkerResource resource to create

	*/
	WorkerResource *models.WorkerResource
	/*BaseSpaceID
	  ID of the space

	*/
	BaseSpaceID string
	/*ID
	  ID of the WorkerResource to modify

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update worker spaces params
func (o *UpdateWorkerSpacesParams) WithTimeout(timeout time.Duration) *UpdateWorkerSpacesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update worker spaces params
func (o *UpdateWorkerSpacesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update worker spaces params
func (o *UpdateWorkerSpacesParams) WithContext(ctx context.Context) *UpdateWorkerSpacesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update worker spaces params
func (o *UpdateWorkerSpacesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update worker spaces params
func (o *UpdateWorkerSpacesParams) WithHTTPClient(client *http.Client) *UpdateWorkerSpacesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update worker spaces params
func (o *UpdateWorkerSpacesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithWorkerResource adds the workerResource to the update worker spaces params
func (o *UpdateWorkerSpacesParams) WithWorkerResource(workerResource *models.WorkerResource) *UpdateWorkerSpacesParams {
	o.SetWorkerResource(workerResource)
	return o
}

// SetWorkerResource adds the workerResource to the update worker spaces params
func (o *UpdateWorkerSpacesParams) SetWorkerResource(workerResource *models.WorkerResource) {
	o.WorkerResource = workerResource
}

// WithBaseSpaceID adds the baseSpaceID to the update worker spaces params
func (o *UpdateWorkerSpacesParams) WithBaseSpaceID(baseSpaceID string) *UpdateWorkerSpacesParams {
	o.SetBaseSpaceID(baseSpaceID)
	return o
}

// SetBaseSpaceID adds the baseSpaceId to the update worker spaces params
func (o *UpdateWorkerSpacesParams) SetBaseSpaceID(baseSpaceID string) {
	o.BaseSpaceID = baseSpaceID
}

// WithID adds the id to the update worker spaces params
func (o *UpdateWorkerSpacesParams) WithID(id string) *UpdateWorkerSpacesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update worker spaces params
func (o *UpdateWorkerSpacesParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateWorkerSpacesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.WorkerResource != nil {
		if err := r.SetBodyParam(o.WorkerResource); err != nil {
			return err
		}
	}

	// path param baseSpaceId
	if err := r.SetPathParam("baseSpaceId", o.BaseSpaceID); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
