// Code generated by go-swagger; DO NOT EDIT.

package artifacts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// CreateArtifactReader is a Reader for the CreateArtifact structure.
type CreateArtifactReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateArtifactReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateArtifactCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateArtifactBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateArtifactCreated creates a CreateArtifactCreated with default headers values
func NewCreateArtifactCreated() *CreateArtifactCreated {
	return &CreateArtifactCreated{}
}

/*CreateArtifactCreated handles this case with default header values.

ArtifactResource Created
*/
type CreateArtifactCreated struct {
	Payload *models.ArtifactResource
}

func (o *CreateArtifactCreated) Error() string {
	return fmt.Sprintf("[POST /api/artifacts][%d] createArtifactCreated  %+v", 201, o.Payload)
}

func (o *CreateArtifactCreated) GetPayload() *models.ArtifactResource {
	return o.Payload
}

func (o *CreateArtifactCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ArtifactResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateArtifactBadRequest creates a CreateArtifactBadRequest with default headers values
func NewCreateArtifactBadRequest() *CreateArtifactBadRequest {
	return &CreateArtifactBadRequest{}
}

/*CreateArtifactBadRequest handles this case with default header values.

Model validation failed.
No request body was supplied.
*/
type CreateArtifactBadRequest struct {
}

func (o *CreateArtifactBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/artifacts][%d] createArtifactBadRequest ", 400)
}

func (o *CreateArtifactBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
