// Code generated by go-swagger; DO NOT EDIT.

package runbook_snapshots

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// GetRunbookSnapshotByProjectAndNameReader is a Reader for the GetRunbookSnapshotByProjectAndName structure.
type GetRunbookSnapshotByProjectAndNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRunbookSnapshotByProjectAndNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetRunbookSnapshotByProjectAndNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetRunbookSnapshotByProjectAndNameBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetRunbookSnapshotByProjectAndNameOK creates a GetRunbookSnapshotByProjectAndNameOK with default headers values
func NewGetRunbookSnapshotByProjectAndNameOK() *GetRunbookSnapshotByProjectAndNameOK {
	return &GetRunbookSnapshotByProjectAndNameOK{}
}

/*GetRunbookSnapshotByProjectAndNameOK handles this case with default header values.

RunbookSnapshotResource resource returned
*/
type GetRunbookSnapshotByProjectAndNameOK struct {
	Payload *models.RunbookSnapshotResource
}

func (o *GetRunbookSnapshotByProjectAndNameOK) Error() string {
	return fmt.Sprintf("[GET /api/projects/{id}/runbookSnapshots/{name}][%d] getRunbookSnapshotByProjectAndNameOK  %+v", 200, o.Payload)
}

func (o *GetRunbookSnapshotByProjectAndNameOK) GetPayload() *models.RunbookSnapshotResource {
	return o.Payload
}

func (o *GetRunbookSnapshotByProjectAndNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RunbookSnapshotResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRunbookSnapshotByProjectAndNameBadRequest creates a GetRunbookSnapshotByProjectAndNameBadRequest with default headers values
func NewGetRunbookSnapshotByProjectAndNameBadRequest() *GetRunbookSnapshotByProjectAndNameBadRequest {
	return &GetRunbookSnapshotByProjectAndNameBadRequest{}
}

/*GetRunbookSnapshotByProjectAndNameBadRequest handles this case with default header values.

No id parameter was provided.
No name parameter was provided.
*/
type GetRunbookSnapshotByProjectAndNameBadRequest struct {
}

func (o *GetRunbookSnapshotByProjectAndNameBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/projects/{id}/runbookSnapshots/{name}][%d] getRunbookSnapshotByProjectAndNameBadRequest ", 400)
}

func (o *GetRunbookSnapshotByProjectAndNameBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
