// Code generated by go-swagger; DO NOT EDIT.

package action_templates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// CreateActionTemplateActionsSpacesReader is a Reader for the CreateActionTemplateActionsSpaces structure.
type CreateActionTemplateActionsSpacesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateActionTemplateActionsSpacesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateActionTemplateActionsSpacesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateActionTemplateActionsSpacesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateActionTemplateActionsSpacesOK creates a CreateActionTemplateActionsSpacesOK with default headers values
func NewCreateActionTemplateActionsSpacesOK() *CreateActionTemplateActionsSpacesOK {
	return &CreateActionTemplateActionsSpacesOK{}
}

/*CreateActionTemplateActionsSpacesOK handles this case with default header values.

ActionUpdateResultResource[] resource returned
*/
type CreateActionTemplateActionsSpacesOK struct {
	Payload []*models.ActionUpdateResultResource
}

func (o *CreateActionTemplateActionsSpacesOK) Error() string {
	return fmt.Sprintf("[POST /api/{baseSpaceId}/actiontemplates/{id}/actionsUpdate][%d] createActionTemplateActionsSpacesOK  %+v", 200, o.Payload)
}

func (o *CreateActionTemplateActionsSpacesOK) GetPayload() []*models.ActionUpdateResultResource {
	return o.Payload
}

func (o *CreateActionTemplateActionsSpacesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateActionTemplateActionsSpacesBadRequest creates a CreateActionTemplateActionsSpacesBadRequest with default headers values
func NewCreateActionTemplateActionsSpacesBadRequest() *CreateActionTemplateActionsSpacesBadRequest {
	return &CreateActionTemplateActionsSpacesBadRequest{}
}

/*CreateActionTemplateActionsSpacesBadRequest handles this case with default header values.

No id parameter was provided.
No request body was supplied.
Request failed. Please check Details property for more information.
Validation failed.
*/
type CreateActionTemplateActionsSpacesBadRequest struct {
}

func (o *CreateActionTemplateActionsSpacesBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/{baseSpaceId}/actiontemplates/{id}/actionsUpdate][%d] createActionTemplateActionsSpacesBadRequest ", 400)
}

func (o *CreateActionTemplateActionsSpacesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
