// Code generated by go-swagger; DO NOT EDIT.

package action_templates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteActionTemplateSpacesParams creates a new DeleteActionTemplateSpacesParams object
// with the default values initialized.
func NewDeleteActionTemplateSpacesParams() *DeleteActionTemplateSpacesParams {
	var ()
	return &DeleteActionTemplateSpacesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteActionTemplateSpacesParamsWithTimeout creates a new DeleteActionTemplateSpacesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteActionTemplateSpacesParamsWithTimeout(timeout time.Duration) *DeleteActionTemplateSpacesParams {
	var ()
	return &DeleteActionTemplateSpacesParams{

		timeout: timeout,
	}
}

// NewDeleteActionTemplateSpacesParamsWithContext creates a new DeleteActionTemplateSpacesParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteActionTemplateSpacesParamsWithContext(ctx context.Context) *DeleteActionTemplateSpacesParams {
	var ()
	return &DeleteActionTemplateSpacesParams{

		Context: ctx,
	}
}

// NewDeleteActionTemplateSpacesParamsWithHTTPClient creates a new DeleteActionTemplateSpacesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteActionTemplateSpacesParamsWithHTTPClient(client *http.Client) *DeleteActionTemplateSpacesParams {
	var ()
	return &DeleteActionTemplateSpacesParams{
		HTTPClient: client,
	}
}

/*DeleteActionTemplateSpacesParams contains all the parameters to send to the API endpoint
for the delete action template spaces operation typically these are written to a http.Request
*/
type DeleteActionTemplateSpacesParams struct {

	/*BaseSpaceID
	  ID of the space

	*/
	BaseSpaceID string
	/*ID
	  ID of the ActionTemplateResource to delete

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete action template spaces params
func (o *DeleteActionTemplateSpacesParams) WithTimeout(timeout time.Duration) *DeleteActionTemplateSpacesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete action template spaces params
func (o *DeleteActionTemplateSpacesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete action template spaces params
func (o *DeleteActionTemplateSpacesParams) WithContext(ctx context.Context) *DeleteActionTemplateSpacesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete action template spaces params
func (o *DeleteActionTemplateSpacesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete action template spaces params
func (o *DeleteActionTemplateSpacesParams) WithHTTPClient(client *http.Client) *DeleteActionTemplateSpacesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete action template spaces params
func (o *DeleteActionTemplateSpacesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBaseSpaceID adds the baseSpaceID to the delete action template spaces params
func (o *DeleteActionTemplateSpacesParams) WithBaseSpaceID(baseSpaceID string) *DeleteActionTemplateSpacesParams {
	o.SetBaseSpaceID(baseSpaceID)
	return o
}

// SetBaseSpaceID adds the baseSpaceId to the delete action template spaces params
func (o *DeleteActionTemplateSpacesParams) SetBaseSpaceID(baseSpaceID string) {
	o.BaseSpaceID = baseSpaceID
}

// WithID adds the id to the delete action template spaces params
func (o *DeleteActionTemplateSpacesParams) WithID(id string) *DeleteActionTemplateSpacesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete action template spaces params
func (o *DeleteActionTemplateSpacesParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteActionTemplateSpacesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param baseSpaceId
	if err := r.SetPathParam("baseSpaceId", o.BaseSpaceID); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
