// Code generated by go-swagger; DO NOT EDIT.

package action_templates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetActionTemplateLogoVersionParams creates a new GetActionTemplateLogoVersionParams object
// with the default values initialized.
func NewGetActionTemplateLogoVersionParams() *GetActionTemplateLogoVersionParams {
	var ()
	return &GetActionTemplateLogoVersionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetActionTemplateLogoVersionParamsWithTimeout creates a new GetActionTemplateLogoVersionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetActionTemplateLogoVersionParamsWithTimeout(timeout time.Duration) *GetActionTemplateLogoVersionParams {
	var ()
	return &GetActionTemplateLogoVersionParams{

		timeout: timeout,
	}
}

// NewGetActionTemplateLogoVersionParamsWithContext creates a new GetActionTemplateLogoVersionParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetActionTemplateLogoVersionParamsWithContext(ctx context.Context) *GetActionTemplateLogoVersionParams {
	var ()
	return &GetActionTemplateLogoVersionParams{

		Context: ctx,
	}
}

// NewGetActionTemplateLogoVersionParamsWithHTTPClient creates a new GetActionTemplateLogoVersionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetActionTemplateLogoVersionParamsWithHTTPClient(client *http.Client) *GetActionTemplateLogoVersionParams {
	var ()
	return &GetActionTemplateLogoVersionParams{
		HTTPClient: client,
	}
}

/*GetActionTemplateLogoVersionParams contains all the parameters to send to the API endpoint
for the get action template logo version operation typically these are written to a http.Request
*/
type GetActionTemplateLogoVersionParams struct {

	/*TypeOrID
	  Action Type or ID of the action type logo

	*/
	TypeOrID string
	/*Version
	  Version of the action type logo

	*/
	Version int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get action template logo version params
func (o *GetActionTemplateLogoVersionParams) WithTimeout(timeout time.Duration) *GetActionTemplateLogoVersionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get action template logo version params
func (o *GetActionTemplateLogoVersionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get action template logo version params
func (o *GetActionTemplateLogoVersionParams) WithContext(ctx context.Context) *GetActionTemplateLogoVersionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get action template logo version params
func (o *GetActionTemplateLogoVersionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get action template logo version params
func (o *GetActionTemplateLogoVersionParams) WithHTTPClient(client *http.Client) *GetActionTemplateLogoVersionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get action template logo version params
func (o *GetActionTemplateLogoVersionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTypeOrID adds the typeOrID to the get action template logo version params
func (o *GetActionTemplateLogoVersionParams) WithTypeOrID(typeOrID string) *GetActionTemplateLogoVersionParams {
	o.SetTypeOrID(typeOrID)
	return o
}

// SetTypeOrID adds the typeOrId to the get action template logo version params
func (o *GetActionTemplateLogoVersionParams) SetTypeOrID(typeOrID string) {
	o.TypeOrID = typeOrID
}

// WithVersion adds the version to the get action template logo version params
func (o *GetActionTemplateLogoVersionParams) WithVersion(version int32) *GetActionTemplateLogoVersionParams {
	o.SetVersion(version)
	return o
}

// SetVersion adds the version to the get action template logo version params
func (o *GetActionTemplateLogoVersionParams) SetVersion(version int32) {
	o.Version = version
}

// WriteToRequest writes these params to a swagger request
func (o *GetActionTemplateLogoVersionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param typeOrId
	if err := r.SetPathParam("typeOrId", o.TypeOrID); err != nil {
		return err
	}

	// path param version
	if err := r.SetPathParam("version", swag.FormatInt32(o.Version)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
