// Code generated by go-swagger; DO NOT EDIT.

package action_templates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// GetActionTemplateUsageReader is a Reader for the GetActionTemplateUsage structure.
type GetActionTemplateUsageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetActionTemplateUsageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetActionTemplateUsageOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetActionTemplateUsageBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetActionTemplateUsageOK creates a GetActionTemplateUsageOK with default headers values
func NewGetActionTemplateUsageOK() *GetActionTemplateUsageOK {
	return &GetActionTemplateUsageOK{}
}

/*GetActionTemplateUsageOK handles this case with default header values.

ActionTemplateUsageResource[] resource returned
*/
type GetActionTemplateUsageOK struct {
	Payload []*models.ActionTemplateUsageResource
}

func (o *GetActionTemplateUsageOK) Error() string {
	return fmt.Sprintf("[GET /api/actiontemplates/{id}/usage][%d] getActionTemplateUsageOK  %+v", 200, o.Payload)
}

func (o *GetActionTemplateUsageOK) GetPayload() []*models.ActionTemplateUsageResource {
	return o.Payload
}

func (o *GetActionTemplateUsageOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetActionTemplateUsageBadRequest creates a GetActionTemplateUsageBadRequest with default headers values
func NewGetActionTemplateUsageBadRequest() *GetActionTemplateUsageBadRequest {
	return &GetActionTemplateUsageBadRequest{}
}

/*GetActionTemplateUsageBadRequest handles this case with default header values.

No id parameter was provided.
*/
type GetActionTemplateUsageBadRequest struct {
}

func (o *GetActionTemplateUsageBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/actiontemplates/{id}/usage][%d] getActionTemplateUsageBadRequest ", 400)
}

func (o *GetActionTemplateUsageBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
