// Code generated by go-swagger; DO NOT EDIT.

package tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCreateTaskStateSpacesParams creates a new CreateTaskStateSpacesParams object
// with the default values initialized.
func NewCreateTaskStateSpacesParams() *CreateTaskStateSpacesParams {
	var ()
	return &CreateTaskStateSpacesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateTaskStateSpacesParamsWithTimeout creates a new CreateTaskStateSpacesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateTaskStateSpacesParamsWithTimeout(timeout time.Duration) *CreateTaskStateSpacesParams {
	var ()
	return &CreateTaskStateSpacesParams{

		timeout: timeout,
	}
}

// NewCreateTaskStateSpacesParamsWithContext creates a new CreateTaskStateSpacesParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateTaskStateSpacesParamsWithContext(ctx context.Context) *CreateTaskStateSpacesParams {
	var ()
	return &CreateTaskStateSpacesParams{

		Context: ctx,
	}
}

// NewCreateTaskStateSpacesParamsWithHTTPClient creates a new CreateTaskStateSpacesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateTaskStateSpacesParamsWithHTTPClient(client *http.Client) *CreateTaskStateSpacesParams {
	var ()
	return &CreateTaskStateSpacesParams{
		HTTPClient: client,
	}
}

/*CreateTaskStateSpacesParams contains all the parameters to send to the API endpoint
for the create task state spaces operation typically these are written to a http.Request
*/
type CreateTaskStateSpacesParams struct {

	/*BaseSpaceID
	  ID of the space

	*/
	BaseSpaceID string
	/*ID
	  ID of the resource

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create task state spaces params
func (o *CreateTaskStateSpacesParams) WithTimeout(timeout time.Duration) *CreateTaskStateSpacesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create task state spaces params
func (o *CreateTaskStateSpacesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create task state spaces params
func (o *CreateTaskStateSpacesParams) WithContext(ctx context.Context) *CreateTaskStateSpacesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create task state spaces params
func (o *CreateTaskStateSpacesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create task state spaces params
func (o *CreateTaskStateSpacesParams) WithHTTPClient(client *http.Client) *CreateTaskStateSpacesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create task state spaces params
func (o *CreateTaskStateSpacesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBaseSpaceID adds the baseSpaceID to the create task state spaces params
func (o *CreateTaskStateSpacesParams) WithBaseSpaceID(baseSpaceID string) *CreateTaskStateSpacesParams {
	o.SetBaseSpaceID(baseSpaceID)
	return o
}

// SetBaseSpaceID adds the baseSpaceId to the create task state spaces params
func (o *CreateTaskStateSpacesParams) SetBaseSpaceID(baseSpaceID string) {
	o.BaseSpaceID = baseSpaceID
}

// WithID adds the id to the create task state spaces params
func (o *CreateTaskStateSpacesParams) WithID(id string) *CreateTaskStateSpacesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the create task state spaces params
func (o *CreateTaskStateSpacesParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *CreateTaskStateSpacesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param baseSpaceId
	if err := r.SetPathParam("baseSpaceId", o.BaseSpaceID); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
