// Code generated by go-swagger; DO NOT EDIT.

package tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCreateTaskStateParams creates a new CreateTaskStateParams object
// with the default values initialized.
func NewCreateTaskStateParams() *CreateTaskStateParams {
	var ()
	return &CreateTaskStateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateTaskStateParamsWithTimeout creates a new CreateTaskStateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateTaskStateParamsWithTimeout(timeout time.Duration) *CreateTaskStateParams {
	var ()
	return &CreateTaskStateParams{

		timeout: timeout,
	}
}

// NewCreateTaskStateParamsWithContext creates a new CreateTaskStateParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateTaskStateParamsWithContext(ctx context.Context) *CreateTaskStateParams {
	var ()
	return &CreateTaskStateParams{

		Context: ctx,
	}
}

// NewCreateTaskStateParamsWithHTTPClient creates a new CreateTaskStateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateTaskStateParamsWithHTTPClient(client *http.Client) *CreateTaskStateParams {
	var ()
	return &CreateTaskStateParams{
		HTTPClient: client,
	}
}

/*CreateTaskStateParams contains all the parameters to send to the API endpoint
for the create task state operation typically these are written to a http.Request
*/
type CreateTaskStateParams struct {

	/*ID
	  ID of the resource

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create task state params
func (o *CreateTaskStateParams) WithTimeout(timeout time.Duration) *CreateTaskStateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create task state params
func (o *CreateTaskStateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create task state params
func (o *CreateTaskStateParams) WithContext(ctx context.Context) *CreateTaskStateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create task state params
func (o *CreateTaskStateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create task state params
func (o *CreateTaskStateParams) WithHTTPClient(client *http.Client) *CreateTaskStateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create task state params
func (o *CreateTaskStateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the create task state params
func (o *CreateTaskStateParams) WithID(id string) *CreateTaskStateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the create task state params
func (o *CreateTaskStateParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *CreateTaskStateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
