// Code generated by go-swagger; DO NOT EDIT.

package tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// CreateTaskCancelSpacesReader is a Reader for the CreateTaskCancelSpaces structure.
type CreateTaskCancelSpacesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateTaskCancelSpacesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateTaskCancelSpacesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateTaskCancelSpacesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateTaskCancelSpacesOK creates a CreateTaskCancelSpacesOK with default headers values
func NewCreateTaskCancelSpacesOK() *CreateTaskCancelSpacesOK {
	return &CreateTaskCancelSpacesOK{}
}

/*CreateTaskCancelSpacesOK handles this case with default header values.

TaskResource resource returned
*/
type CreateTaskCancelSpacesOK struct {
	Payload *models.TaskResource
}

func (o *CreateTaskCancelSpacesOK) Error() string {
	return fmt.Sprintf("[POST /api/{baseSpaceId}/tasks/{id}/cancel][%d] createTaskCancelSpacesOK  %+v", 200, o.Payload)
}

func (o *CreateTaskCancelSpacesOK) GetPayload() *models.TaskResource {
	return o.Payload
}

func (o *CreateTaskCancelSpacesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TaskResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateTaskCancelSpacesBadRequest creates a CreateTaskCancelSpacesBadRequest with default headers values
func NewCreateTaskCancelSpacesBadRequest() *CreateTaskCancelSpacesBadRequest {
	return &CreateTaskCancelSpacesBadRequest{}
}

/*CreateTaskCancelSpacesBadRequest handles this case with default header values.

No id parameter was provided.
*/
type CreateTaskCancelSpacesBadRequest struct {
}

func (o *CreateTaskCancelSpacesBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/{baseSpaceId}/tasks/{id}/cancel][%d] createTaskCancelSpacesBadRequest ", 400)
}

func (o *CreateTaskCancelSpacesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
