// Code generated by go-swagger; DO NOT EDIT.

package tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// CreateTaskRerunReader is a Reader for the CreateTaskRerun structure.
type CreateTaskRerunReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateTaskRerunReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateTaskRerunOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateTaskRerunBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateTaskRerunOK creates a CreateTaskRerunOK with default headers values
func NewCreateTaskRerunOK() *CreateTaskRerunOK {
	return &CreateTaskRerunOK{}
}

/*CreateTaskRerunOK handles this case with default header values.

TaskResource resource returned
*/
type CreateTaskRerunOK struct {
	Payload *models.TaskResource
}

func (o *CreateTaskRerunOK) Error() string {
	return fmt.Sprintf("[POST /api/tasks/rerun/{id}][%d] createTaskRerunOK  %+v", 200, o.Payload)
}

func (o *CreateTaskRerunOK) GetPayload() *models.TaskResource {
	return o.Payload
}

func (o *CreateTaskRerunOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TaskResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateTaskRerunBadRequest creates a CreateTaskRerunBadRequest with default headers values
func NewCreateTaskRerunBadRequest() *CreateTaskRerunBadRequest {
	return &CreateTaskRerunBadRequest{}
}

/*CreateTaskRerunBadRequest handles this case with default header values.

No id parameter was provided.
This task cannot be re-run.
*/
type CreateTaskRerunBadRequest struct {
}

func (o *CreateTaskRerunBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/tasks/rerun/{id}][%d] createTaskRerunBadRequest ", 400)
}

func (o *CreateTaskRerunBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
