// Code generated by go-swagger; DO NOT EDIT.

package tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// GetListTasksReader is a Reader for the GetListTasks structure.
type GetListTasksReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetListTasksReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetListTasksOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetListTasksOK creates a GetListTasksOK with default headers values
func NewGetListTasksOK() *GetListTasksOK {
	return &GetListTasksOK{}
}

/*GetListTasksOK handles this case with default header values.

ResourceCollection_of_TaskResource resource returned
*/
type GetListTasksOK struct {
	Payload *models.ResourceCollectionOfTaskResource
}

func (o *GetListTasksOK) Error() string {
	return fmt.Sprintf("[GET /api/tasks][%d] getListTasksOK  %+v", 200, o.Payload)
}

func (o *GetListTasksOK) GetPayload() *models.ResourceCollectionOfTaskResource {
	return o.Payload
}

func (o *GetListTasksOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResourceCollectionOfTaskResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
