// Code generated by go-swagger; DO NOT EDIT.

package tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetTaskRawSpacesReader is a Reader for the GetTaskRawSpaces structure.
type GetTaskRawSpacesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTaskRawSpacesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTaskRawSpacesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetTaskRawSpacesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetTaskRawSpacesOK creates a GetTaskRawSpacesOK with default headers values
func NewGetTaskRawSpacesOK() *GetTaskRawSpacesOK {
	return &GetTaskRawSpacesOK{}
}

/*GetTaskRawSpacesOK handles this case with default header values.

OK
*/
type GetTaskRawSpacesOK struct {
}

func (o *GetTaskRawSpacesOK) Error() string {
	return fmt.Sprintf("[GET /api/{baseSpaceId}/tasks/{id}/raw][%d] getTaskRawSpacesOK ", 200)
}

func (o *GetTaskRawSpacesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetTaskRawSpacesBadRequest creates a GetTaskRawSpacesBadRequest with default headers values
func NewGetTaskRawSpacesBadRequest() *GetTaskRawSpacesBadRequest {
	return &GetTaskRawSpacesBadRequest{}
}

/*GetTaskRawSpacesBadRequest handles this case with default header values.

No id parameter was provided.
*/
type GetTaskRawSpacesBadRequest struct {
}

func (o *GetTaskRawSpacesBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/{baseSpaceId}/tasks/{id}/raw][%d] getTaskRawSpacesBadRequest ", 400)
}

func (o *GetTaskRawSpacesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
