// Code generated by go-swagger; DO NOT EDIT.

package library_variable_sets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetLibraryVariableSetUsageListSpacesParams creates a new GetLibraryVariableSetUsageListSpacesParams object
// with the default values initialized.
func NewGetLibraryVariableSetUsageListSpacesParams() *GetLibraryVariableSetUsageListSpacesParams {
	var ()
	return &GetLibraryVariableSetUsageListSpacesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetLibraryVariableSetUsageListSpacesParamsWithTimeout creates a new GetLibraryVariableSetUsageListSpacesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetLibraryVariableSetUsageListSpacesParamsWithTimeout(timeout time.Duration) *GetLibraryVariableSetUsageListSpacesParams {
	var ()
	return &GetLibraryVariableSetUsageListSpacesParams{

		timeout: timeout,
	}
}

// NewGetLibraryVariableSetUsageListSpacesParamsWithContext creates a new GetLibraryVariableSetUsageListSpacesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetLibraryVariableSetUsageListSpacesParamsWithContext(ctx context.Context) *GetLibraryVariableSetUsageListSpacesParams {
	var ()
	return &GetLibraryVariableSetUsageListSpacesParams{

		Context: ctx,
	}
}

// NewGetLibraryVariableSetUsageListSpacesParamsWithHTTPClient creates a new GetLibraryVariableSetUsageListSpacesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetLibraryVariableSetUsageListSpacesParamsWithHTTPClient(client *http.Client) *GetLibraryVariableSetUsageListSpacesParams {
	var ()
	return &GetLibraryVariableSetUsageListSpacesParams{
		HTTPClient: client,
	}
}

/*GetLibraryVariableSetUsageListSpacesParams contains all the parameters to send to the API endpoint
for the get library variable set usage list spaces operation typically these are written to a http.Request
*/
type GetLibraryVariableSetUsageListSpacesParams struct {

	/*BaseSpaceID
	  ID of the space

	*/
	BaseSpaceID string
	/*ID
	  ID of the resource

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get library variable set usage list spaces params
func (o *GetLibraryVariableSetUsageListSpacesParams) WithTimeout(timeout time.Duration) *GetLibraryVariableSetUsageListSpacesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get library variable set usage list spaces params
func (o *GetLibraryVariableSetUsageListSpacesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get library variable set usage list spaces params
func (o *GetLibraryVariableSetUsageListSpacesParams) WithContext(ctx context.Context) *GetLibraryVariableSetUsageListSpacesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get library variable set usage list spaces params
func (o *GetLibraryVariableSetUsageListSpacesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get library variable set usage list spaces params
func (o *GetLibraryVariableSetUsageListSpacesParams) WithHTTPClient(client *http.Client) *GetLibraryVariableSetUsageListSpacesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get library variable set usage list spaces params
func (o *GetLibraryVariableSetUsageListSpacesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBaseSpaceID adds the baseSpaceID to the get library variable set usage list spaces params
func (o *GetLibraryVariableSetUsageListSpacesParams) WithBaseSpaceID(baseSpaceID string) *GetLibraryVariableSetUsageListSpacesParams {
	o.SetBaseSpaceID(baseSpaceID)
	return o
}

// SetBaseSpaceID adds the baseSpaceId to the get library variable set usage list spaces params
func (o *GetLibraryVariableSetUsageListSpacesParams) SetBaseSpaceID(baseSpaceID string) {
	o.BaseSpaceID = baseSpaceID
}

// WithID adds the id to the get library variable set usage list spaces params
func (o *GetLibraryVariableSetUsageListSpacesParams) WithID(id string) *GetLibraryVariableSetUsageListSpacesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get library variable set usage list spaces params
func (o *GetLibraryVariableSetUsageListSpacesParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetLibraryVariableSetUsageListSpacesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param baseSpaceId
	if err := r.SetPathParam("baseSpaceId", o.BaseSpaceID); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
