// Code generated by go-swagger; DO NOT EDIT.

package library_variable_sets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// GetLibraryVariableSetByIDReader is a Reader for the GetLibraryVariableSetByID structure.
type GetLibraryVariableSetByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLibraryVariableSetByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetLibraryVariableSetByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetLibraryVariableSetByIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetLibraryVariableSetByIDOK creates a GetLibraryVariableSetByIDOK with default headers values
func NewGetLibraryVariableSetByIDOK() *GetLibraryVariableSetByIDOK {
	return &GetLibraryVariableSetByIDOK{}
}

/*GetLibraryVariableSetByIDOK handles this case with default header values.

Load LibraryVariableSetResource by ID
*/
type GetLibraryVariableSetByIDOK struct {
	Payload *models.LibraryVariableSetResource
}

func (o *GetLibraryVariableSetByIDOK) Error() string {
	return fmt.Sprintf("[GET /api/libraryvariablesets/{id}][%d] getLibraryVariableSetByIdOK  %+v", 200, o.Payload)
}

func (o *GetLibraryVariableSetByIDOK) GetPayload() *models.LibraryVariableSetResource {
	return o.Payload
}

func (o *GetLibraryVariableSetByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.LibraryVariableSetResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetLibraryVariableSetByIDBadRequest creates a GetLibraryVariableSetByIDBadRequest with default headers values
func NewGetLibraryVariableSetByIDBadRequest() *GetLibraryVariableSetByIDBadRequest {
	return &GetLibraryVariableSetByIDBadRequest{}
}

/*GetLibraryVariableSetByIDBadRequest handles this case with default header values.

No id parameter was provided.
*/
type GetLibraryVariableSetByIDBadRequest struct {
}

func (o *GetLibraryVariableSetByIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/libraryvariablesets/{id}][%d] getLibraryVariableSetByIdBadRequest ", 400)
}

func (o *GetLibraryVariableSetByIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
