// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// GetUserAuthenticationReader is a Reader for the GetUserAuthentication structure.
type GetUserAuthenticationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetUserAuthenticationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetUserAuthenticationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetUserAuthenticationOK creates a GetUserAuthenticationOK with default headers values
func NewGetUserAuthenticationOK() *GetUserAuthenticationOK {
	return &GetUserAuthenticationOK{}
}

/*GetUserAuthenticationOK handles this case with default header values.

UserAuthenticationResource resource returned
*/
type GetUserAuthenticationOK struct {
	Payload *models.UserAuthenticationResource
}

func (o *GetUserAuthenticationOK) Error() string {
	return fmt.Sprintf("[GET /api/users/authentication][%d] getUserAuthenticationOK  %+v", 200, o.Payload)
}

func (o *GetUserAuthenticationOK) GetPayload() *models.UserAuthenticationResource {
	return o.Payload
}

func (o *GetUserAuthenticationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UserAuthenticationResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
