// Code generated by go-swagger; DO NOT EDIT.

package environments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListAllEnvironmentsParams creates a new ListAllEnvironmentsParams object
// with the default values initialized.
func NewListAllEnvironmentsParams() *ListAllEnvironmentsParams {

	return &ListAllEnvironmentsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListAllEnvironmentsParamsWithTimeout creates a new ListAllEnvironmentsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListAllEnvironmentsParamsWithTimeout(timeout time.Duration) *ListAllEnvironmentsParams {

	return &ListAllEnvironmentsParams{

		timeout: timeout,
	}
}

// NewListAllEnvironmentsParamsWithContext creates a new ListAllEnvironmentsParams object
// with the default values initialized, and the ability to set a context for a request
func NewListAllEnvironmentsParamsWithContext(ctx context.Context) *ListAllEnvironmentsParams {

	return &ListAllEnvironmentsParams{

		Context: ctx,
	}
}

// NewListAllEnvironmentsParamsWithHTTPClient creates a new ListAllEnvironmentsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListAllEnvironmentsParamsWithHTTPClient(client *http.Client) *ListAllEnvironmentsParams {

	return &ListAllEnvironmentsParams{
		HTTPClient: client,
	}
}

/*ListAllEnvironmentsParams contains all the parameters to send to the API endpoint
for the list all environments operation typically these are written to a http.Request
*/
type ListAllEnvironmentsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list all environments params
func (o *ListAllEnvironmentsParams) WithTimeout(timeout time.Duration) *ListAllEnvironmentsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list all environments params
func (o *ListAllEnvironmentsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list all environments params
func (o *ListAllEnvironmentsParams) WithContext(ctx context.Context) *ListAllEnvironmentsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list all environments params
func (o *ListAllEnvironmentsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list all environments params
func (o *ListAllEnvironmentsParams) WithHTTPClient(client *http.Client) *ListAllEnvironmentsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list all environments params
func (o *ListAllEnvironmentsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ListAllEnvironmentsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
