// Code generated by go-swagger; DO NOT EDIT.

package environments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// UpdateEnvironmentSpacesReader is a Reader for the UpdateEnvironmentSpaces structure.
type UpdateEnvironmentSpacesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateEnvironmentSpacesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateEnvironmentSpacesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateEnvironmentSpacesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateEnvironmentSpacesOK creates a UpdateEnvironmentSpacesOK with default headers values
func NewUpdateEnvironmentSpacesOK() *UpdateEnvironmentSpacesOK {
	return &UpdateEnvironmentSpacesOK{}
}

/*UpdateEnvironmentSpacesOK handles this case with default header values.

EnvironmentResource Modified
*/
type UpdateEnvironmentSpacesOK struct {
	Payload *models.EnvironmentResource
}

func (o *UpdateEnvironmentSpacesOK) Error() string {
	return fmt.Sprintf("[PUT /api/{baseSpaceId}/environments/{id}][%d] updateEnvironmentSpacesOK  %+v", 200, o.Payload)
}

func (o *UpdateEnvironmentSpacesOK) GetPayload() *models.EnvironmentResource {
	return o.Payload
}

func (o *UpdateEnvironmentSpacesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EnvironmentResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateEnvironmentSpacesBadRequest creates a UpdateEnvironmentSpacesBadRequest with default headers values
func NewUpdateEnvironmentSpacesBadRequest() *UpdateEnvironmentSpacesBadRequest {
	return &UpdateEnvironmentSpacesBadRequest{}
}

/*UpdateEnvironmentSpacesBadRequest handles this case with default header values.

Model validation failed.
No id parameter was provided.
No request body was supplied.
This resource is read-only and cannot be modified.
*/
type UpdateEnvironmentSpacesBadRequest struct {
}

func (o *UpdateEnvironmentSpacesBadRequest) Error() string {
	return fmt.Sprintf("[PUT /api/{baseSpaceId}/environments/{id}][%d] updateEnvironmentSpacesBadRequest ", 400)
}

func (o *UpdateEnvironmentSpacesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
