// Code generated by go-swagger; DO NOT EDIT.

package tenants

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetTenantLogoSpacesParams creates a new GetTenantLogoSpacesParams object
// with the default values initialized.
func NewGetTenantLogoSpacesParams() *GetTenantLogoSpacesParams {
	var ()
	return &GetTenantLogoSpacesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetTenantLogoSpacesParamsWithTimeout creates a new GetTenantLogoSpacesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetTenantLogoSpacesParamsWithTimeout(timeout time.Duration) *GetTenantLogoSpacesParams {
	var ()
	return &GetTenantLogoSpacesParams{

		timeout: timeout,
	}
}

// NewGetTenantLogoSpacesParamsWithContext creates a new GetTenantLogoSpacesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetTenantLogoSpacesParamsWithContext(ctx context.Context) *GetTenantLogoSpacesParams {
	var ()
	return &GetTenantLogoSpacesParams{

		Context: ctx,
	}
}

// NewGetTenantLogoSpacesParamsWithHTTPClient creates a new GetTenantLogoSpacesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetTenantLogoSpacesParamsWithHTTPClient(client *http.Client) *GetTenantLogoSpacesParams {
	var ()
	return &GetTenantLogoSpacesParams{
		HTTPClient: client,
	}
}

/*GetTenantLogoSpacesParams contains all the parameters to send to the API endpoint
for the get tenant logo spaces operation typically these are written to a http.Request
*/
type GetTenantLogoSpacesParams struct {

	/*BaseSpaceID
	  ID of the space

	*/
	BaseSpaceID string
	/*ID
	  ID of the resource

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get tenant logo spaces params
func (o *GetTenantLogoSpacesParams) WithTimeout(timeout time.Duration) *GetTenantLogoSpacesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get tenant logo spaces params
func (o *GetTenantLogoSpacesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get tenant logo spaces params
func (o *GetTenantLogoSpacesParams) WithContext(ctx context.Context) *GetTenantLogoSpacesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get tenant logo spaces params
func (o *GetTenantLogoSpacesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get tenant logo spaces params
func (o *GetTenantLogoSpacesParams) WithHTTPClient(client *http.Client) *GetTenantLogoSpacesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get tenant logo spaces params
func (o *GetTenantLogoSpacesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBaseSpaceID adds the baseSpaceID to the get tenant logo spaces params
func (o *GetTenantLogoSpacesParams) WithBaseSpaceID(baseSpaceID string) *GetTenantLogoSpacesParams {
	o.SetBaseSpaceID(baseSpaceID)
	return o
}

// SetBaseSpaceID adds the baseSpaceId to the get tenant logo spaces params
func (o *GetTenantLogoSpacesParams) SetBaseSpaceID(baseSpaceID string) {
	o.BaseSpaceID = baseSpaceID
}

// WithID adds the id to the get tenant logo spaces params
func (o *GetTenantLogoSpacesParams) WithID(id string) *GetTenantLogoSpacesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get tenant logo spaces params
func (o *GetTenantLogoSpacesParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetTenantLogoSpacesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param baseSpaceId
	if err := r.SetPathParam("baseSpaceId", o.BaseSpaceID); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
