// Code generated by go-swagger; DO NOT EDIT.

package tenants

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetTenantVariablesMissingParams creates a new GetTenantVariablesMissingParams object
// with the default values initialized.
func NewGetTenantVariablesMissingParams() *GetTenantVariablesMissingParams {

	return &GetTenantVariablesMissingParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetTenantVariablesMissingParamsWithTimeout creates a new GetTenantVariablesMissingParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetTenantVariablesMissingParamsWithTimeout(timeout time.Duration) *GetTenantVariablesMissingParams {

	return &GetTenantVariablesMissingParams{

		timeout: timeout,
	}
}

// NewGetTenantVariablesMissingParamsWithContext creates a new GetTenantVariablesMissingParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetTenantVariablesMissingParamsWithContext(ctx context.Context) *GetTenantVariablesMissingParams {

	return &GetTenantVariablesMissingParams{

		Context: ctx,
	}
}

// NewGetTenantVariablesMissingParamsWithHTTPClient creates a new GetTenantVariablesMissingParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetTenantVariablesMissingParamsWithHTTPClient(client *http.Client) *GetTenantVariablesMissingParams {

	return &GetTenantVariablesMissingParams{
		HTTPClient: client,
	}
}

/*GetTenantVariablesMissingParams contains all the parameters to send to the API endpoint
for the get tenant variables missing operation typically these are written to a http.Request
*/
type GetTenantVariablesMissingParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get tenant variables missing params
func (o *GetTenantVariablesMissingParams) WithTimeout(timeout time.Duration) *GetTenantVariablesMissingParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get tenant variables missing params
func (o *GetTenantVariablesMissingParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get tenant variables missing params
func (o *GetTenantVariablesMissingParams) WithContext(ctx context.Context) *GetTenantVariablesMissingParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get tenant variables missing params
func (o *GetTenantVariablesMissingParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get tenant variables missing params
func (o *GetTenantVariablesMissingParams) WithHTTPClient(client *http.Client) *GetTenantVariablesMissingParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get tenant variables missing params
func (o *GetTenantVariablesMissingParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetTenantVariablesMissingParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
