// Code generated by go-swagger; DO NOT EDIT.

package tenants

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// GetTenantByIDSpacesReader is a Reader for the GetTenantByIDSpaces structure.
type GetTenantByIDSpacesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTenantByIDSpacesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTenantByIDSpacesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetTenantByIDSpacesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetTenantByIDSpacesOK creates a GetTenantByIDSpacesOK with default headers values
func NewGetTenantByIDSpacesOK() *GetTenantByIDSpacesOK {
	return &GetTenantByIDSpacesOK{}
}

/*GetTenantByIDSpacesOK handles this case with default header values.

Load TenantResource by ID
*/
type GetTenantByIDSpacesOK struct {
	Payload *models.TenantResource
}

func (o *GetTenantByIDSpacesOK) Error() string {
	return fmt.Sprintf("[GET /api/{baseSpaceId}/tenants/{id}][%d] getTenantByIdSpacesOK  %+v", 200, o.Payload)
}

func (o *GetTenantByIDSpacesOK) GetPayload() *models.TenantResource {
	return o.Payload
}

func (o *GetTenantByIDSpacesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TenantResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTenantByIDSpacesBadRequest creates a GetTenantByIDSpacesBadRequest with default headers values
func NewGetTenantByIDSpacesBadRequest() *GetTenantByIDSpacesBadRequest {
	return &GetTenantByIDSpacesBadRequest{}
}

/*GetTenantByIDSpacesBadRequest handles this case with default header values.

No id parameter was provided.
*/
type GetTenantByIDSpacesBadRequest struct {
}

func (o *GetTenantByIDSpacesBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/{baseSpaceId}/tenants/{id}][%d] getTenantByIdSpacesBadRequest ", 400)
}

func (o *GetTenantByIDSpacesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
