// Code generated by go-swagger; DO NOT EDIT.

package runbook_runs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteRunbookRunSpacesReader is a Reader for the DeleteRunbookRunSpaces structure.
type DeleteRunbookRunSpacesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteRunbookRunSpacesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteRunbookRunSpacesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteRunbookRunSpacesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteRunbookRunSpacesOK creates a DeleteRunbookRunSpacesOK with default headers values
func NewDeleteRunbookRunSpacesOK() *DeleteRunbookRunSpacesOK {
	return &DeleteRunbookRunSpacesOK{}
}

/*DeleteRunbookRunSpacesOK handles this case with default header values.

OK
*/
type DeleteRunbookRunSpacesOK struct {
}

func (o *DeleteRunbookRunSpacesOK) Error() string {
	return fmt.Sprintf("[DELETE /api/{baseSpaceId}/runbookRuns/{id}][%d] deleteRunbookRunSpacesOK ", 200)
}

func (o *DeleteRunbookRunSpacesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteRunbookRunSpacesBadRequest creates a DeleteRunbookRunSpacesBadRequest with default headers values
func NewDeleteRunbookRunSpacesBadRequest() *DeleteRunbookRunSpacesBadRequest {
	return &DeleteRunbookRunSpacesBadRequest{}
}

/*DeleteRunbookRunSpacesBadRequest handles this case with default header values.

BadRequest
No id parameter was provided.
This resource is read-only and cannot be deleted.
*/
type DeleteRunbookRunSpacesBadRequest struct {
}

func (o *DeleteRunbookRunSpacesBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /api/{baseSpaceId}/runbookRuns/{id}][%d] deleteRunbookRunSpacesBadRequest ", 400)
}

func (o *DeleteRunbookRunSpacesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
