// Code generated by go-swagger; DO NOT EDIT.

package proxies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"models"
)

// NewUpdateProxyParams creates a new UpdateProxyParams object
// with the default values initialized.
func NewUpdateProxyParams() *UpdateProxyParams {
	var ()
	return &UpdateProxyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateProxyParamsWithTimeout creates a new UpdateProxyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateProxyParamsWithTimeout(timeout time.Duration) *UpdateProxyParams {
	var ()
	return &UpdateProxyParams{

		timeout: timeout,
	}
}

// NewUpdateProxyParamsWithContext creates a new UpdateProxyParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateProxyParamsWithContext(ctx context.Context) *UpdateProxyParams {
	var ()
	return &UpdateProxyParams{

		Context: ctx,
	}
}

// NewUpdateProxyParamsWithHTTPClient creates a new UpdateProxyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateProxyParamsWithHTTPClient(client *http.Client) *UpdateProxyParams {
	var ()
	return &UpdateProxyParams{
		HTTPClient: client,
	}
}

/*UpdateProxyParams contains all the parameters to send to the API endpoint
for the update proxy operation typically these are written to a http.Request
*/
type UpdateProxyParams struct {

	/*ProxyResource
	  The ProxyResource resource to create

	*/
	ProxyResource *models.ProxyResource
	/*ID
	  ID of the ProxyResource to modify

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update proxy params
func (o *UpdateProxyParams) WithTimeout(timeout time.Duration) *UpdateProxyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update proxy params
func (o *UpdateProxyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update proxy params
func (o *UpdateProxyParams) WithContext(ctx context.Context) *UpdateProxyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update proxy params
func (o *UpdateProxyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update proxy params
func (o *UpdateProxyParams) WithHTTPClient(client *http.Client) *UpdateProxyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update proxy params
func (o *UpdateProxyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProxyResource adds the proxyResource to the update proxy params
func (o *UpdateProxyParams) WithProxyResource(proxyResource *models.ProxyResource) *UpdateProxyParams {
	o.SetProxyResource(proxyResource)
	return o
}

// SetProxyResource adds the proxyResource to the update proxy params
func (o *UpdateProxyParams) SetProxyResource(proxyResource *models.ProxyResource) {
	o.ProxyResource = proxyResource
}

// WithID adds the id to the update proxy params
func (o *UpdateProxyParams) WithID(id string) *UpdateProxyParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update proxy params
func (o *UpdateProxyParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateProxyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ProxyResource != nil {
		if err := r.SetBodyParam(o.ProxyResource); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
