// Code generated by go-swagger; DO NOT EDIT.

package proxies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// UpdateProxySpacesReader is a Reader for the UpdateProxySpaces structure.
type UpdateProxySpacesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateProxySpacesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateProxySpacesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateProxySpacesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateProxySpacesOK creates a UpdateProxySpacesOK with default headers values
func NewUpdateProxySpacesOK() *UpdateProxySpacesOK {
	return &UpdateProxySpacesOK{}
}

/*UpdateProxySpacesOK handles this case with default header values.

ProxyResource Modified
*/
type UpdateProxySpacesOK struct {
	Payload *models.ProxyResource
}

func (o *UpdateProxySpacesOK) Error() string {
	return fmt.Sprintf("[PUT /api/{baseSpaceId}/proxies/{id}][%d] updateProxySpacesOK  %+v", 200, o.Payload)
}

func (o *UpdateProxySpacesOK) GetPayload() *models.ProxyResource {
	return o.Payload
}

func (o *UpdateProxySpacesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProxyResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateProxySpacesBadRequest creates a UpdateProxySpacesBadRequest with default headers values
func NewUpdateProxySpacesBadRequest() *UpdateProxySpacesBadRequest {
	return &UpdateProxySpacesBadRequest{}
}

/*UpdateProxySpacesBadRequest handles this case with default header values.

Model validation failed.
No id parameter was provided.
No request body was supplied.
This resource is read-only and cannot be modified.
*/
type UpdateProxySpacesBadRequest struct {
}

func (o *UpdateProxySpacesBadRequest) Error() string {
	return fmt.Sprintf("[PUT /api/{baseSpaceId}/proxies/{id}][%d] updateProxySpacesBadRequest ", 400)
}

func (o *UpdateProxySpacesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
