// Code generated by go-swagger; DO NOT EDIT.

package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// GetConfigurationSectionListReader is a Reader for the GetConfigurationSectionList structure.
type GetConfigurationSectionListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetConfigurationSectionListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetConfigurationSectionListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetConfigurationSectionListOK creates a GetConfigurationSectionListOK with default headers values
func NewGetConfigurationSectionListOK() *GetConfigurationSectionListOK {
	return &GetConfigurationSectionListOK{}
}

/*GetConfigurationSectionListOK handles this case with default header values.

ResourceCollection_of_ConfigurationSectionMetadata resource returned
*/
type GetConfigurationSectionListOK struct {
	Payload *models.ResourceCollectionOfConfigurationSectionMetadata
}

func (o *GetConfigurationSectionListOK) Error() string {
	return fmt.Sprintf("[GET /api/configuration][%d] getConfigurationSectionListOK  %+v", 200, o.Payload)
}

func (o *GetConfigurationSectionListOK) GetPayload() *models.ResourceCollectionOfConfigurationSectionMetadata {
	return o.Payload
}

func (o *GetConfigurationSectionListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResourceCollectionOfConfigurationSectionMetadata)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
