// Code generated by go-swagger; DO NOT EDIT.

package feeds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteFeedSpacesParams creates a new DeleteFeedSpacesParams object
// with the default values initialized.
func NewDeleteFeedSpacesParams() *DeleteFeedSpacesParams {
	var ()
	return &DeleteFeedSpacesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteFeedSpacesParamsWithTimeout creates a new DeleteFeedSpacesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteFeedSpacesParamsWithTimeout(timeout time.Duration) *DeleteFeedSpacesParams {
	var ()
	return &DeleteFeedSpacesParams{

		timeout: timeout,
	}
}

// NewDeleteFeedSpacesParamsWithContext creates a new DeleteFeedSpacesParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteFeedSpacesParamsWithContext(ctx context.Context) *DeleteFeedSpacesParams {
	var ()
	return &DeleteFeedSpacesParams{

		Context: ctx,
	}
}

// NewDeleteFeedSpacesParamsWithHTTPClient creates a new DeleteFeedSpacesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteFeedSpacesParamsWithHTTPClient(client *http.Client) *DeleteFeedSpacesParams {
	var ()
	return &DeleteFeedSpacesParams{
		HTTPClient: client,
	}
}

/*DeleteFeedSpacesParams contains all the parameters to send to the API endpoint
for the delete feed spaces operation typically these are written to a http.Request
*/
type DeleteFeedSpacesParams struct {

	/*BaseSpaceID
	  ID of the space

	*/
	BaseSpaceID string
	/*ID
	  ID of the FeedResource to delete

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete feed spaces params
func (o *DeleteFeedSpacesParams) WithTimeout(timeout time.Duration) *DeleteFeedSpacesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete feed spaces params
func (o *DeleteFeedSpacesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete feed spaces params
func (o *DeleteFeedSpacesParams) WithContext(ctx context.Context) *DeleteFeedSpacesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete feed spaces params
func (o *DeleteFeedSpacesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete feed spaces params
func (o *DeleteFeedSpacesParams) WithHTTPClient(client *http.Client) *DeleteFeedSpacesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete feed spaces params
func (o *DeleteFeedSpacesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBaseSpaceID adds the baseSpaceID to the delete feed spaces params
func (o *DeleteFeedSpacesParams) WithBaseSpaceID(baseSpaceID string) *DeleteFeedSpacesParams {
	o.SetBaseSpaceID(baseSpaceID)
	return o
}

// SetBaseSpaceID adds the baseSpaceId to the delete feed spaces params
func (o *DeleteFeedSpacesParams) SetBaseSpaceID(baseSpaceID string) {
	o.BaseSpaceID = baseSpaceID
}

// WithID adds the id to the delete feed spaces params
func (o *DeleteFeedSpacesParams) WithID(id string) *DeleteFeedSpacesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete feed spaces params
func (o *DeleteFeedSpacesParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteFeedSpacesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param baseSpaceId
	if err := r.SetPathParam("baseSpaceId", o.BaseSpaceID); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
