// Code generated by go-swagger; DO NOT EDIT.

package feeds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// GetPackageSearchSpacesReader is a Reader for the GetPackageSearchSpaces structure.
type GetPackageSearchSpacesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPackageSearchSpacesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPackageSearchSpacesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetPackageSearchSpacesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetPackageSearchSpacesOK creates a GetPackageSearchSpacesOK with default headers values
func NewGetPackageSearchSpacesOK() *GetPackageSearchSpacesOK {
	return &GetPackageSearchSpacesOK{}
}

/*GetPackageSearchSpacesOK handles this case with default header values.

ResourceCollection_of_PackageDescriptionResource resource returned
*/
type GetPackageSearchSpacesOK struct {
	Payload *models.ResourceCollectionOfPackageDescriptionResource
}

func (o *GetPackageSearchSpacesOK) Error() string {
	return fmt.Sprintf("[GET /api/{baseSpaceId}/feeds/{id}/packages/search][%d] getPackageSearchSpacesOK  %+v", 200, o.Payload)
}

func (o *GetPackageSearchSpacesOK) GetPayload() *models.ResourceCollectionOfPackageDescriptionResource {
	return o.Payload
}

func (o *GetPackageSearchSpacesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResourceCollectionOfPackageDescriptionResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPackageSearchSpacesBadRequest creates a GetPackageSearchSpacesBadRequest with default headers values
func NewGetPackageSearchSpacesBadRequest() *GetPackageSearchSpacesBadRequest {
	return &GetPackageSearchSpacesBadRequest{}
}

/*GetPackageSearchSpacesBadRequest handles this case with default header values.

No id parameter was provided.
*/
type GetPackageSearchSpacesBadRequest struct {
}

func (o *GetPackageSearchSpacesBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/{baseSpaceId}/feeds/{id}/packages/search][%d] getPackageSearchSpacesBadRequest ", 400)
}

func (o *GetPackageSearchSpacesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
