// Code generated by go-swagger; DO NOT EDIT.

package feeds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// GetFeedByIDReader is a Reader for the GetFeedByID structure.
type GetFeedByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetFeedByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetFeedByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetFeedByIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetFeedByIDOK creates a GetFeedByIDOK with default headers values
func NewGetFeedByIDOK() *GetFeedByIDOK {
	return &GetFeedByIDOK{}
}

/*GetFeedByIDOK handles this case with default header values.

Load FeedResource by ID
*/
type GetFeedByIDOK struct {
	Payload *models.FeedResource
}

func (o *GetFeedByIDOK) Error() string {
	return fmt.Sprintf("[GET /api/feeds/{id}][%d] getFeedByIdOK  %+v", 200, o.Payload)
}

func (o *GetFeedByIDOK) GetPayload() *models.FeedResource {
	return o.Payload
}

func (o *GetFeedByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FeedResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetFeedByIDBadRequest creates a GetFeedByIDBadRequest with default headers values
func NewGetFeedByIDBadRequest() *GetFeedByIDBadRequest {
	return &GetFeedByIDBadRequest{}
}

/*GetFeedByIDBadRequest handles this case with default header values.

No id parameter was provided.
*/
type GetFeedByIDBadRequest struct {
}

func (o *GetFeedByIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/feeds/{id}][%d] getFeedByIdBadRequest ", 400)
}

func (o *GetFeedByIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
