// Code generated by go-swagger; DO NOT EDIT.

package dashboard_configurations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// UpdateDashboardConfigurationReader is a Reader for the UpdateDashboardConfiguration structure.
type UpdateDashboardConfigurationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateDashboardConfigurationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateDashboardConfigurationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateDashboardConfigurationBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateDashboardConfigurationOK creates a UpdateDashboardConfigurationOK with default headers values
func NewUpdateDashboardConfigurationOK() *UpdateDashboardConfigurationOK {
	return &UpdateDashboardConfigurationOK{}
}

/*UpdateDashboardConfigurationOK handles this case with default header values.

DashboardConfigurationResource resource returned
*/
type UpdateDashboardConfigurationOK struct {
	Payload *models.DashboardConfigurationResource
}

func (o *UpdateDashboardConfigurationOK) Error() string {
	return fmt.Sprintf("[PUT /api/dashboardconfiguration][%d] updateDashboardConfigurationOK  %+v", 200, o.Payload)
}

func (o *UpdateDashboardConfigurationOK) GetPayload() *models.DashboardConfigurationResource {
	return o.Payload
}

func (o *UpdateDashboardConfigurationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DashboardConfigurationResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateDashboardConfigurationBadRequest creates a UpdateDashboardConfigurationBadRequest with default headers values
func NewUpdateDashboardConfigurationBadRequest() *UpdateDashboardConfigurationBadRequest {
	return &UpdateDashboardConfigurationBadRequest{}
}

/*UpdateDashboardConfigurationBadRequest handles this case with default header values.

No request body was supplied.
*/
type UpdateDashboardConfigurationBadRequest struct {
}

func (o *UpdateDashboardConfigurationBadRequest) Error() string {
	return fmt.Sprintf("[PUT /api/dashboardconfiguration][%d] updateDashboardConfigurationBadRequest ", 400)
}

func (o *UpdateDashboardConfigurationBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
