// Code generated by go-swagger; DO NOT EDIT.

package teams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// GetTeamByIDSpacesReader is a Reader for the GetTeamByIDSpaces structure.
type GetTeamByIDSpacesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTeamByIDSpacesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTeamByIDSpacesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetTeamByIDSpacesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetTeamByIDSpacesOK creates a GetTeamByIDSpacesOK with default headers values
func NewGetTeamByIDSpacesOK() *GetTeamByIDSpacesOK {
	return &GetTeamByIDSpacesOK{}
}

/*GetTeamByIDSpacesOK handles this case with default header values.

Load TeamResource by ID
*/
type GetTeamByIDSpacesOK struct {
	Payload *models.TeamResource
}

func (o *GetTeamByIDSpacesOK) Error() string {
	return fmt.Sprintf("[GET /api/{baseSpaceId}/teams/{id}][%d] getTeamByIdSpacesOK  %+v", 200, o.Payload)
}

func (o *GetTeamByIDSpacesOK) GetPayload() *models.TeamResource {
	return o.Payload
}

func (o *GetTeamByIDSpacesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TeamResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTeamByIDSpacesBadRequest creates a GetTeamByIDSpacesBadRequest with default headers values
func NewGetTeamByIDSpacesBadRequest() *GetTeamByIDSpacesBadRequest {
	return &GetTeamByIDSpacesBadRequest{}
}

/*GetTeamByIDSpacesBadRequest handles this case with default header values.

No id parameter was provided.
*/
type GetTeamByIDSpacesBadRequest struct {
}

func (o *GetTeamByIDSpacesBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/{baseSpaceId}/teams/{id}][%d] getTeamByIdSpacesBadRequest ", 400)
}

func (o *GetTeamByIDSpacesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
