// Code generated by go-swagger; DO NOT EDIT.

package teams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// GetListScopedUserRoleForTeamReader is a Reader for the GetListScopedUserRoleForTeam structure.
type GetListScopedUserRoleForTeamReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetListScopedUserRoleForTeamReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetListScopedUserRoleForTeamOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetListScopedUserRoleForTeamBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetListScopedUserRoleForTeamOK creates a GetListScopedUserRoleForTeamOK with default headers values
func NewGetListScopedUserRoleForTeamOK() *GetListScopedUserRoleForTeamOK {
	return &GetListScopedUserRoleForTeamOK{}
}

/*GetListScopedUserRoleForTeamOK handles this case with default header values.

ResourceCollection_of_ScopedUserRoleResource resource returned
*/
type GetListScopedUserRoleForTeamOK struct {
	Payload *models.ResourceCollectionOfScopedUserRoleResource
}

func (o *GetListScopedUserRoleForTeamOK) Error() string {
	return fmt.Sprintf("[GET /api/teams/{id}/scopeduserroles][%d] getListScopedUserRoleForTeamOK  %+v", 200, o.Payload)
}

func (o *GetListScopedUserRoleForTeamOK) GetPayload() *models.ResourceCollectionOfScopedUserRoleResource {
	return o.Payload
}

func (o *GetListScopedUserRoleForTeamOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResourceCollectionOfScopedUserRoleResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetListScopedUserRoleForTeamBadRequest creates a GetListScopedUserRoleForTeamBadRequest with default headers values
func NewGetListScopedUserRoleForTeamBadRequest() *GetListScopedUserRoleForTeamBadRequest {
	return &GetListScopedUserRoleForTeamBadRequest{}
}

/*GetListScopedUserRoleForTeamBadRequest handles this case with default header values.

No id parameter was provided.
*/
type GetListScopedUserRoleForTeamBadRequest struct {
}

func (o *GetListScopedUserRoleForTeamBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/teams/{id}/scopeduserroles][%d] getListScopedUserRoleForTeamBadRequest ", 400)
}

func (o *GetListScopedUserRoleForTeamBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
