// Code generated by go-swagger; DO NOT EDIT.

package teams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListAllTeamsSpacesParams creates a new ListAllTeamsSpacesParams object
// with the default values initialized.
func NewListAllTeamsSpacesParams() *ListAllTeamsSpacesParams {
	var ()
	return &ListAllTeamsSpacesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListAllTeamsSpacesParamsWithTimeout creates a new ListAllTeamsSpacesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListAllTeamsSpacesParamsWithTimeout(timeout time.Duration) *ListAllTeamsSpacesParams {
	var ()
	return &ListAllTeamsSpacesParams{

		timeout: timeout,
	}
}

// NewListAllTeamsSpacesParamsWithContext creates a new ListAllTeamsSpacesParams object
// with the default values initialized, and the ability to set a context for a request
func NewListAllTeamsSpacesParamsWithContext(ctx context.Context) *ListAllTeamsSpacesParams {
	var ()
	return &ListAllTeamsSpacesParams{

		Context: ctx,
	}
}

// NewListAllTeamsSpacesParamsWithHTTPClient creates a new ListAllTeamsSpacesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListAllTeamsSpacesParamsWithHTTPClient(client *http.Client) *ListAllTeamsSpacesParams {
	var ()
	return &ListAllTeamsSpacesParams{
		HTTPClient: client,
	}
}

/*ListAllTeamsSpacesParams contains all the parameters to send to the API endpoint
for the list all teams spaces operation typically these are written to a http.Request
*/
type ListAllTeamsSpacesParams struct {

	/*BaseSpaceID
	  ID of the space

	*/
	BaseSpaceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list all teams spaces params
func (o *ListAllTeamsSpacesParams) WithTimeout(timeout time.Duration) *ListAllTeamsSpacesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list all teams spaces params
func (o *ListAllTeamsSpacesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list all teams spaces params
func (o *ListAllTeamsSpacesParams) WithContext(ctx context.Context) *ListAllTeamsSpacesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list all teams spaces params
func (o *ListAllTeamsSpacesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list all teams spaces params
func (o *ListAllTeamsSpacesParams) WithHTTPClient(client *http.Client) *ListAllTeamsSpacesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list all teams spaces params
func (o *ListAllTeamsSpacesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBaseSpaceID adds the baseSpaceID to the list all teams spaces params
func (o *ListAllTeamsSpacesParams) WithBaseSpaceID(baseSpaceID string) *ListAllTeamsSpacesParams {
	o.SetBaseSpaceID(baseSpaceID)
	return o
}

// SetBaseSpaceID adds the baseSpaceId to the list all teams spaces params
func (o *ListAllTeamsSpacesParams) SetBaseSpaceID(baseSpaceID string) {
	o.BaseSpaceID = baseSpaceID
}

// WriteToRequest writes these params to a swagger request
func (o *ListAllTeamsSpacesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param baseSpaceId
	if err := r.SetPathParam("baseSpaceId", o.BaseSpaceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
