// Code generated by go-swagger; DO NOT EDIT.

package runbook_processes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetRunbookSnapshotTemplateForRunbookStepParams creates a new GetRunbookSnapshotTemplateForRunbookStepParams object
// with the default values initialized.
func NewGetRunbookSnapshotTemplateForRunbookStepParams() *GetRunbookSnapshotTemplateForRunbookStepParams {
	var ()
	return &GetRunbookSnapshotTemplateForRunbookStepParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRunbookSnapshotTemplateForRunbookStepParamsWithTimeout creates a new GetRunbookSnapshotTemplateForRunbookStepParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRunbookSnapshotTemplateForRunbookStepParamsWithTimeout(timeout time.Duration) *GetRunbookSnapshotTemplateForRunbookStepParams {
	var ()
	return &GetRunbookSnapshotTemplateForRunbookStepParams{

		timeout: timeout,
	}
}

// NewGetRunbookSnapshotTemplateForRunbookStepParamsWithContext creates a new GetRunbookSnapshotTemplateForRunbookStepParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRunbookSnapshotTemplateForRunbookStepParamsWithContext(ctx context.Context) *GetRunbookSnapshotTemplateForRunbookStepParams {
	var ()
	return &GetRunbookSnapshotTemplateForRunbookStepParams{

		Context: ctx,
	}
}

// NewGetRunbookSnapshotTemplateForRunbookStepParamsWithHTTPClient creates a new GetRunbookSnapshotTemplateForRunbookStepParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRunbookSnapshotTemplateForRunbookStepParamsWithHTTPClient(client *http.Client) *GetRunbookSnapshotTemplateForRunbookStepParams {
	var ()
	return &GetRunbookSnapshotTemplateForRunbookStepParams{
		HTTPClient: client,
	}
}

/*GetRunbookSnapshotTemplateForRunbookStepParams contains all the parameters to send to the API endpoint
for the get runbook snapshot template for runbook step operation typically these are written to a http.Request
*/
type GetRunbookSnapshotTemplateForRunbookStepParams struct {

	/*ID
	  ID of the resource

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get runbook snapshot template for runbook step params
func (o *GetRunbookSnapshotTemplateForRunbookStepParams) WithTimeout(timeout time.Duration) *GetRunbookSnapshotTemplateForRunbookStepParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get runbook snapshot template for runbook step params
func (o *GetRunbookSnapshotTemplateForRunbookStepParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get runbook snapshot template for runbook step params
func (o *GetRunbookSnapshotTemplateForRunbookStepParams) WithContext(ctx context.Context) *GetRunbookSnapshotTemplateForRunbookStepParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get runbook snapshot template for runbook step params
func (o *GetRunbookSnapshotTemplateForRunbookStepParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get runbook snapshot template for runbook step params
func (o *GetRunbookSnapshotTemplateForRunbookStepParams) WithHTTPClient(client *http.Client) *GetRunbookSnapshotTemplateForRunbookStepParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get runbook snapshot template for runbook step params
func (o *GetRunbookSnapshotTemplateForRunbookStepParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get runbook snapshot template for runbook step params
func (o *GetRunbookSnapshotTemplateForRunbookStepParams) WithID(id string) *GetRunbookSnapshotTemplateForRunbookStepParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get runbook snapshot template for runbook step params
func (o *GetRunbookSnapshotTemplateForRunbookStepParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetRunbookSnapshotTemplateForRunbookStepParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
