// Code generated by go-swagger; DO NOT EDIT.

package runbook_processes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUpdateRunbookProcessSpacesParams creates a new UpdateRunbookProcessSpacesParams object
// with the default values initialized.
func NewUpdateRunbookProcessSpacesParams() *UpdateRunbookProcessSpacesParams {
	var ()
	return &UpdateRunbookProcessSpacesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateRunbookProcessSpacesParamsWithTimeout creates a new UpdateRunbookProcessSpacesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateRunbookProcessSpacesParamsWithTimeout(timeout time.Duration) *UpdateRunbookProcessSpacesParams {
	var ()
	return &UpdateRunbookProcessSpacesParams{

		timeout: timeout,
	}
}

// NewUpdateRunbookProcessSpacesParamsWithContext creates a new UpdateRunbookProcessSpacesParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateRunbookProcessSpacesParamsWithContext(ctx context.Context) *UpdateRunbookProcessSpacesParams {
	var ()
	return &UpdateRunbookProcessSpacesParams{

		Context: ctx,
	}
}

// NewUpdateRunbookProcessSpacesParamsWithHTTPClient creates a new UpdateRunbookProcessSpacesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateRunbookProcessSpacesParamsWithHTTPClient(client *http.Client) *UpdateRunbookProcessSpacesParams {
	var ()
	return &UpdateRunbookProcessSpacesParams{
		HTTPClient: client,
	}
}

/*UpdateRunbookProcessSpacesParams contains all the parameters to send to the API endpoint
for the update runbook process spaces operation typically these are written to a http.Request
*/
type UpdateRunbookProcessSpacesParams struct {

	/*BaseSpaceID
	  ID of the space

	*/
	BaseSpaceID string
	/*ID
	  ID of the resource

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update runbook process spaces params
func (o *UpdateRunbookProcessSpacesParams) WithTimeout(timeout time.Duration) *UpdateRunbookProcessSpacesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update runbook process spaces params
func (o *UpdateRunbookProcessSpacesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update runbook process spaces params
func (o *UpdateRunbookProcessSpacesParams) WithContext(ctx context.Context) *UpdateRunbookProcessSpacesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update runbook process spaces params
func (o *UpdateRunbookProcessSpacesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update runbook process spaces params
func (o *UpdateRunbookProcessSpacesParams) WithHTTPClient(client *http.Client) *UpdateRunbookProcessSpacesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update runbook process spaces params
func (o *UpdateRunbookProcessSpacesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBaseSpaceID adds the baseSpaceID to the update runbook process spaces params
func (o *UpdateRunbookProcessSpacesParams) WithBaseSpaceID(baseSpaceID string) *UpdateRunbookProcessSpacesParams {
	o.SetBaseSpaceID(baseSpaceID)
	return o
}

// SetBaseSpaceID adds the baseSpaceId to the update runbook process spaces params
func (o *UpdateRunbookProcessSpacesParams) SetBaseSpaceID(baseSpaceID string) {
	o.BaseSpaceID = baseSpaceID
}

// WithID adds the id to the update runbook process spaces params
func (o *UpdateRunbookProcessSpacesParams) WithID(id string) *UpdateRunbookProcessSpacesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update runbook process spaces params
func (o *UpdateRunbookProcessSpacesParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateRunbookProcessSpacesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param baseSpaceId
	if err := r.SetPathParam("baseSpaceId", o.BaseSpaceID); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
