// Code generated by go-swagger; DO NOT EDIT.

package scheduler

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetScheduledTaskDetailsParams creates a new GetScheduledTaskDetailsParams object
// with the default values initialized.
func NewGetScheduledTaskDetailsParams() *GetScheduledTaskDetailsParams {
	var ()
	return &GetScheduledTaskDetailsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetScheduledTaskDetailsParamsWithTimeout creates a new GetScheduledTaskDetailsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetScheduledTaskDetailsParamsWithTimeout(timeout time.Duration) *GetScheduledTaskDetailsParams {
	var ()
	return &GetScheduledTaskDetailsParams{

		timeout: timeout,
	}
}

// NewGetScheduledTaskDetailsParamsWithContext creates a new GetScheduledTaskDetailsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetScheduledTaskDetailsParamsWithContext(ctx context.Context) *GetScheduledTaskDetailsParams {
	var ()
	return &GetScheduledTaskDetailsParams{

		Context: ctx,
	}
}

// NewGetScheduledTaskDetailsParamsWithHTTPClient creates a new GetScheduledTaskDetailsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetScheduledTaskDetailsParamsWithHTTPClient(client *http.Client) *GetScheduledTaskDetailsParams {
	var ()
	return &GetScheduledTaskDetailsParams{
		HTTPClient: client,
	}
}

/*GetScheduledTaskDetailsParams contains all the parameters to send to the API endpoint
for the get scheduled task details operation typically these are written to a http.Request
*/
type GetScheduledTaskDetailsParams struct {

	/*Name
	  Name of the task

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get scheduled task details params
func (o *GetScheduledTaskDetailsParams) WithTimeout(timeout time.Duration) *GetScheduledTaskDetailsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get scheduled task details params
func (o *GetScheduledTaskDetailsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get scheduled task details params
func (o *GetScheduledTaskDetailsParams) WithContext(ctx context.Context) *GetScheduledTaskDetailsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get scheduled task details params
func (o *GetScheduledTaskDetailsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get scheduled task details params
func (o *GetScheduledTaskDetailsParams) WithHTTPClient(client *http.Client) *GetScheduledTaskDetailsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get scheduled task details params
func (o *GetScheduledTaskDetailsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get scheduled task details params
func (o *GetScheduledTaskDetailsParams) WithName(name string) *GetScheduledTaskDetailsParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get scheduled task details params
func (o *GetScheduledTaskDetailsParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetScheduledTaskDetailsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
