// Code generated by go-swagger; DO NOT EDIT.

package scheduler

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetScheduledTaskRawDetailsParams creates a new GetScheduledTaskRawDetailsParams object
// with the default values initialized.
func NewGetScheduledTaskRawDetailsParams() *GetScheduledTaskRawDetailsParams {
	var ()
	return &GetScheduledTaskRawDetailsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetScheduledTaskRawDetailsParamsWithTimeout creates a new GetScheduledTaskRawDetailsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetScheduledTaskRawDetailsParamsWithTimeout(timeout time.Duration) *GetScheduledTaskRawDetailsParams {
	var ()
	return &GetScheduledTaskRawDetailsParams{

		timeout: timeout,
	}
}

// NewGetScheduledTaskRawDetailsParamsWithContext creates a new GetScheduledTaskRawDetailsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetScheduledTaskRawDetailsParamsWithContext(ctx context.Context) *GetScheduledTaskRawDetailsParams {
	var ()
	return &GetScheduledTaskRawDetailsParams{

		Context: ctx,
	}
}

// NewGetScheduledTaskRawDetailsParamsWithHTTPClient creates a new GetScheduledTaskRawDetailsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetScheduledTaskRawDetailsParamsWithHTTPClient(client *http.Client) *GetScheduledTaskRawDetailsParams {
	var ()
	return &GetScheduledTaskRawDetailsParams{
		HTTPClient: client,
	}
}

/*GetScheduledTaskRawDetailsParams contains all the parameters to send to the API endpoint
for the get scheduled task raw details operation typically these are written to a http.Request
*/
type GetScheduledTaskRawDetailsParams struct {

	/*Name
	  Name of the scheduled task

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get scheduled task raw details params
func (o *GetScheduledTaskRawDetailsParams) WithTimeout(timeout time.Duration) *GetScheduledTaskRawDetailsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get scheduled task raw details params
func (o *GetScheduledTaskRawDetailsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get scheduled task raw details params
func (o *GetScheduledTaskRawDetailsParams) WithContext(ctx context.Context) *GetScheduledTaskRawDetailsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get scheduled task raw details params
func (o *GetScheduledTaskRawDetailsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get scheduled task raw details params
func (o *GetScheduledTaskRawDetailsParams) WithHTTPClient(client *http.Client) *GetScheduledTaskRawDetailsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get scheduled task raw details params
func (o *GetScheduledTaskRawDetailsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get scheduled task raw details params
func (o *GetScheduledTaskRawDetailsParams) WithName(name string) *GetScheduledTaskRawDetailsParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get scheduled task raw details params
func (o *GetScheduledTaskRawDetailsParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetScheduledTaskRawDetailsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
