// Code generated by go-swagger; DO NOT EDIT.

package machine_roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new machine roles API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for machine roles API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	GetMachineRolesListAll(params *GetMachineRolesListAllParams, authInfo runtime.ClientAuthInfoWriter) (*GetMachineRolesListAllOK, error)

	GetMachineRolesListAllSpaces(params *GetMachineRolesListAllSpacesParams, authInfo runtime.ClientAuthInfoWriter) (*GetMachineRolesListAllSpacesOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GetMachineRolesListAll Gets all machine roles that have been defined in this Octopus installation. The result will be a string array.
*/
func (a *Client) GetMachineRolesListAll(params *GetMachineRolesListAllParams, authInfo runtime.ClientAuthInfoWriter) (*GetMachineRolesListAllOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetMachineRolesListAllParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getMachineRolesListAll",
		Method:             "GET",
		PathPattern:        "/api/machineroles/all",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetMachineRolesListAllReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetMachineRolesListAllOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getMachineRolesListAll: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetMachineRolesListAllSpaces Gets all machine roles that have been defined in this Octopus installation. The result will be a string array.
*/
func (a *Client) GetMachineRolesListAllSpaces(params *GetMachineRolesListAllSpacesParams, authInfo runtime.ClientAuthInfoWriter) (*GetMachineRolesListAllSpacesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetMachineRolesListAllSpacesParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getMachineRolesListAll_Spaces",
		Method:             "GET",
		PathPattern:        "/api/{baseSpaceId}/machineroles/all",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetMachineRolesListAllSpacesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetMachineRolesListAllSpacesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getMachineRolesListAll_Spaces: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
