// Code generated by go-swagger; DO NOT EDIT.

package events

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// GetListEventCategoriesSpacesReader is a Reader for the GetListEventCategoriesSpaces structure.
type GetListEventCategoriesSpacesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetListEventCategoriesSpacesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetListEventCategoriesSpacesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetListEventCategoriesSpacesOK creates a GetListEventCategoriesSpacesOK with default headers values
func NewGetListEventCategoriesSpacesOK() *GetListEventCategoriesSpacesOK {
	return &GetListEventCategoriesSpacesOK{}
}

/*GetListEventCategoriesSpacesOK handles this case with default header values.

IEnumerable_of_EventCategoryResource resource returned
*/
type GetListEventCategoriesSpacesOK struct {
	Payload []*models.EventCategoryResource
}

func (o *GetListEventCategoriesSpacesOK) Error() string {
	return fmt.Sprintf("[GET /api/{baseSpaceId}/events/categories][%d] getListEventCategoriesSpacesOK  %+v", 200, o.Payload)
}

func (o *GetListEventCategoriesSpacesOK) GetPayload() []*models.EventCategoryResource {
	return o.Payload
}

func (o *GetListEventCategoriesSpacesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
