// Code generated by go-swagger; DO NOT EDIT.

package events

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// GetEventByIDReader is a Reader for the GetEventByID structure.
type GetEventByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetEventByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetEventByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetEventByIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetEventByIDOK creates a GetEventByIDOK with default headers values
func NewGetEventByIDOK() *GetEventByIDOK {
	return &GetEventByIDOK{}
}

/*GetEventByIDOK handles this case with default header values.

Load EventResource by ID
*/
type GetEventByIDOK struct {
	Payload *models.EventResource
}

func (o *GetEventByIDOK) Error() string {
	return fmt.Sprintf("[GET /api/events/{id}][%d] getEventByIdOK  %+v", 200, o.Payload)
}

func (o *GetEventByIDOK) GetPayload() *models.EventResource {
	return o.Payload
}

func (o *GetEventByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EventResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetEventByIDBadRequest creates a GetEventByIDBadRequest with default headers values
func NewGetEventByIDBadRequest() *GetEventByIDBadRequest {
	return &GetEventByIDBadRequest{}
}

/*GetEventByIDBadRequest handles this case with default header values.

No id parameter was provided.
*/
type GetEventByIDBadRequest struct {
}

func (o *GetEventByIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/events/{id}][%d] getEventByIdBadRequest ", 400)
}

func (o *GetEventByIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
