// Code generated by go-swagger; DO NOT EDIT.

package subscription

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// ListAllSubscriptionsReader is a Reader for the ListAllSubscriptions structure.
type ListAllSubscriptionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListAllSubscriptionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListAllSubscriptionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListAllSubscriptionsOK creates a ListAllSubscriptionsOK with default headers values
func NewListAllSubscriptionsOK() *ListAllSubscriptionsOK {
	return &ListAllSubscriptionsOK{}
}

/*ListAllSubscriptionsOK handles this case with default header values.

Load all SubscriptionResource
*/
type ListAllSubscriptionsOK struct {
	Payload []*models.SubscriptionResource
}

func (o *ListAllSubscriptionsOK) Error() string {
	return fmt.Sprintf("[GET /api/subscriptions/all][%d] listAllSubscriptionsOK  %+v", 200, o.Payload)
}

func (o *ListAllSubscriptionsOK) GetPayload() []*models.SubscriptionResource {
	return o.Payload
}

func (o *ListAllSubscriptionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
