// Code generated by go-swagger; DO NOT EDIT.

package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// GetAzureWebSitesListReader is a Reader for the GetAzureWebSitesList structure.
type GetAzureWebSitesListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAzureWebSitesListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAzureWebSitesListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAzureWebSitesListBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAzureWebSitesListOK creates a GetAzureWebSitesListOK with default headers values
func NewGetAzureWebSitesListOK() *GetAzureWebSitesListOK {
	return &GetAzureWebSitesListOK{}
}

/*GetAzureWebSitesListOK handles this case with default header values.

IEnumerable_of_AzureWebSiteResource_of_AzureWebSitesListAction resource returned
*/
type GetAzureWebSitesListOK struct {
	Payload []*models.AzureWebSiteResourceOfAzureWebSitesListAction
}

func (o *GetAzureWebSitesListOK) Error() string {
	return fmt.Sprintf("[GET /api/accounts/{id}/websites][%d] getAzureWebSitesListOK  %+v", 200, o.Payload)
}

func (o *GetAzureWebSitesListOK) GetPayload() []*models.AzureWebSiteResourceOfAzureWebSitesListAction {
	return o.Payload
}

func (o *GetAzureWebSitesListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAzureWebSitesListBadRequest creates a GetAzureWebSitesListBadRequest with default headers values
func NewGetAzureWebSitesListBadRequest() *GetAzureWebSitesListBadRequest {
	return &GetAzureWebSitesListBadRequest{}
}

/*GetAzureWebSitesListBadRequest handles this case with default header values.

Account must be an Azure account.
No id parameter was provided.
This operation is not supported using Azure Management Certificate authentication. Please try again using an Azure Service Account.
*/
type GetAzureWebSitesListBadRequest struct {
}

func (o *GetAzureWebSitesListBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/accounts/{id}/websites][%d] getAzureWebSitesListBadRequest ", 400)
}

func (o *GetAzureWebSitesListBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
