// Code generated by go-swagger; DO NOT EDIT.

package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// GetAccountByIDReader is a Reader for the GetAccountByID structure.
type GetAccountByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAccountByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAccountByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAccountByIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAccountByIDOK creates a GetAccountByIDOK with default headers values
func NewGetAccountByIDOK() *GetAccountByIDOK {
	return &GetAccountByIDOK{}
}

/*GetAccountByIDOK handles this case with default header values.

Load AccountResource by ID
*/
type GetAccountByIDOK struct {
	Payload *models.AccountResource
}

func (o *GetAccountByIDOK) Error() string {
	return fmt.Sprintf("[GET /api/accounts/{id}][%d] getAccountByIdOK  %+v", 200, o.Payload)
}

func (o *GetAccountByIDOK) GetPayload() *models.AccountResource {
	return o.Payload
}

func (o *GetAccountByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AccountResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAccountByIDBadRequest creates a GetAccountByIDBadRequest with default headers values
func NewGetAccountByIDBadRequest() *GetAccountByIDBadRequest {
	return &GetAccountByIDBadRequest{}
}

/*GetAccountByIDBadRequest handles this case with default header values.

No id parameter was provided.
*/
type GetAccountByIDBadRequest struct {
}

func (o *GetAccountByIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/accounts/{id}][%d] getAccountByIdBadRequest ", 400)
}

func (o *GetAccountByIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
