// Code generated by go-swagger; DO NOT EDIT.

package deployments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteDeploymentReader is a Reader for the DeleteDeployment structure.
type DeleteDeploymentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteDeploymentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteDeploymentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteDeploymentBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteDeploymentOK creates a DeleteDeploymentOK with default headers values
func NewDeleteDeploymentOK() *DeleteDeploymentOK {
	return &DeleteDeploymentOK{}
}

/*DeleteDeploymentOK handles this case with default header values.

OK
*/
type DeleteDeploymentOK struct {
}

func (o *DeleteDeploymentOK) Error() string {
	return fmt.Sprintf("[DELETE /api/deployments/{id}][%d] deleteDeploymentOK ", 200)
}

func (o *DeleteDeploymentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteDeploymentBadRequest creates a DeleteDeploymentBadRequest with default headers values
func NewDeleteDeploymentBadRequest() *DeleteDeploymentBadRequest {
	return &DeleteDeploymentBadRequest{}
}

/*DeleteDeploymentBadRequest handles this case with default header values.

BadRequest
No id parameter was provided.
This resource is read-only and cannot be deleted.
*/
type DeleteDeploymentBadRequest struct {
}

func (o *DeleteDeploymentBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /api/deployments/{id}][%d] deleteDeploymentBadRequest ", 400)
}

func (o *DeleteDeploymentBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
