// Code generated by go-swagger; DO NOT EDIT.

package deployments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// GetDeploymentByIDSpacesReader is a Reader for the GetDeploymentByIDSpaces structure.
type GetDeploymentByIDSpacesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDeploymentByIDSpacesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDeploymentByIDSpacesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetDeploymentByIDSpacesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetDeploymentByIDSpacesOK creates a GetDeploymentByIDSpacesOK with default headers values
func NewGetDeploymentByIDSpacesOK() *GetDeploymentByIDSpacesOK {
	return &GetDeploymentByIDSpacesOK{}
}

/*GetDeploymentByIDSpacesOK handles this case with default header values.

Load DeploymentResource by ID
*/
type GetDeploymentByIDSpacesOK struct {
	Payload *models.DeploymentResource
}

func (o *GetDeploymentByIDSpacesOK) Error() string {
	return fmt.Sprintf("[GET /api/{baseSpaceId}/deployments/{id}][%d] getDeploymentByIdSpacesOK  %+v", 200, o.Payload)
}

func (o *GetDeploymentByIDSpacesOK) GetPayload() *models.DeploymentResource {
	return o.Payload
}

func (o *GetDeploymentByIDSpacesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeploymentResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDeploymentByIDSpacesBadRequest creates a GetDeploymentByIDSpacesBadRequest with default headers values
func NewGetDeploymentByIDSpacesBadRequest() *GetDeploymentByIDSpacesBadRequest {
	return &GetDeploymentByIDSpacesBadRequest{}
}

/*GetDeploymentByIDSpacesBadRequest handles this case with default header values.

No id parameter was provided.
*/
type GetDeploymentByIDSpacesBadRequest struct {
}

func (o *GetDeploymentByIDSpacesBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/{baseSpaceId}/deployments/{id}][%d] getDeploymentByIdSpacesBadRequest ", 400)
}

func (o *GetDeploymentByIDSpacesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
