// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LibraryVariableSetRunbookSnapshotUsageEntry library variable set runbook snapshot usage entry
//
// swagger:model LibraryVariableSetRunbookSnapshotUsageEntry
type LibraryVariableSetRunbookSnapshotUsageEntry struct {

	// snapshot Id
	SnapshotID string `json:"SnapshotId,omitempty"`

	// snapshot name
	SnapshotName string `json:"SnapshotName,omitempty"`
}

// Validate validates this library variable set runbook snapshot usage entry
func (m *LibraryVariableSetRunbookSnapshotUsageEntry) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LibraryVariableSetRunbookSnapshotUsageEntry) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LibraryVariableSetRunbookSnapshotUsageEntry) UnmarshalBinary(b []byte) error {
	var res LibraryVariableSetRunbookSnapshotUsageEntry
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
