// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PackageSignatureResource package signature resource
//
// swagger:model PackageSignatureResource
type PackageSignatureResource struct {

	// base version
	BaseVersion string `json:"BaseVersion,omitempty"`

	// signature
	// Format: byte
	Signature strfmt.Base64 `json:"Signature,omitempty"`
}

// Validate validates this package signature resource
func (m *PackageSignatureResource) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PackageSignatureResource) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PackageSignatureResource) UnmarshalBinary(b []byte) error {
	var res PackageSignatureResource
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
