// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RunbookStepUsage runbook step usage
//
// swagger:model RunbookStepUsage
type RunbookStepUsage struct {

	// process Id
	ProcessID string `json:"ProcessId,omitempty"`

	// project Id
	ProjectID string `json:"ProjectId,omitempty"`

	// project name
	ProjectName string `json:"ProjectName,omitempty"`

	// project slug
	ProjectSlug string `json:"ProjectSlug,omitempty"`

	// runbook Id
	RunbookID string `json:"RunbookId,omitempty"`

	// runbook name
	RunbookName string `json:"RunbookName,omitempty"`

	// steps
	Steps []*StepUsageEntry `json:"Steps"`
}

// Validate validates this runbook step usage
func (m *RunbookStepUsage) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSteps(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RunbookStepUsage) validateSteps(formats strfmt.Registry) error {

	if swag.IsZero(m.Steps) { // not required
		return nil
	}

	for i := 0; i < len(m.Steps); i++ {
		if swag.IsZero(m.Steps[i]) { // not required
			continue
		}

		if m.Steps[i] != nil {
			if err := m.Steps[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("Steps" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *RunbookStepUsage) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RunbookStepUsage) UnmarshalBinary(b []byte) error {
	var res RunbookStepUsage
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
